///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace Genesis.Provider.Legacy.Desktop.RanorexTests
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The CreateNewItem recording.
    /// </summary>
    [TestModule("14860930-f1a5-4fc1-be5b-fa450d922585", ModuleType.Recording, 1)]
    public partial class CreateNewItem : ITestModule
    {
        /// <summary>
        /// Holds an instance of the Genesis_Provider_Legacy_Desktop_RanorexTestsRepository repository.
        /// </summary>
        public static Genesis_Provider_Legacy_Desktop_RanorexTestsRepository repo = Genesis_Provider_Legacy_Desktop_RanorexTestsRepository.Instance;

        static CreateNewItem instance = new CreateNewItem();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public CreateNewItem()
        {
            NewVariable = "1234587";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static CreateNewItem Instance
        {
            get { return instance; }
        }

#region Variables

        string _NewVariable;

        /// <summary>
        /// Gets or sets the value of variable NewVariable.
        /// </summary>
        [TestVariable("0afd9d35-485c-4bea-9651-c0746876cfe3")]
        public string NewVariable
        {
            get { return _NewVariable; }
            set { _NewVariable = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FrmMain.TransactionData' at 109;18.", repo.FrmMain.TransactionDataInfo, new RecordItemIndex(0));
            repo.FrmMain.TransactionData.Click("109;18");
            Delay.Milliseconds(200);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'GenesisAutomation1.NewItemWizard' at 44;39.", repo.GenesisAutomation1.NewItemWizardInfo, new RecordItemIndex(1));
            //repo.GenesisAutomation1.NewItemWizard.Click("44;39");
            //Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FrmMain.Tasks' at 46;43.", repo.FrmMain.TasksInfo, new RecordItemIndex(2));
            repo.FrmMain.Tasks.Click("46;43");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'PurchaseOrder.BtnNext' at 58;14.", repo.PurchaseOrder.BtnNextInfo, new RecordItemIndex(3));
            repo.PurchaseOrder.BtnNext.Click("58;14");
            Delay.Milliseconds(200);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'PurchaseOrder.WpItem.DdlPreferredSupplier' at 310;16.", repo.PurchaseOrder.WpItem.DdlPreferredSupplierInfo, new RecordItemIndex(4));
            //repo.PurchaseOrder.WpItem.DdlPreferredSupplier.Click("310;16");
            //Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'PurchaseOrder.WpItem.DdlPreferredSupplier' at 310;15.", repo.PurchaseOrder.WpItem.DdlPreferredSupplierInfo, new RecordItemIndex(5));
            repo.PurchaseOrder.WpItem.DdlPreferredSupplier.Click("310;15");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'PurchaseOrder.WpItem.DdlPreferredSupplier'.", repo.PurchaseOrder.WpItem.DdlPreferredSupplierInfo, new RecordItemIndex(6));
            Validate.Exists(repo.PurchaseOrder.WpItem.DdlPreferredSupplierInfo);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'GenesisAutomation.TextMaskBox' at 74;8.", repo.GenesisAutomation.TextMaskBoxInfo, new RecordItemIndex(7));
            repo.GenesisAutomation.TextMaskBox.Click("74;8");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'a' with focus on 'GenesisAutomation.TextMaskBox'.", repo.GenesisAutomation.TextMaskBoxInfo, new RecordItemIndex(8));
            repo.GenesisAutomation.TextMaskBox.PressKeys("a");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'bb' with focus on 'GenesisAutomation.TextMaskBox'.", repo.GenesisAutomation.TextMaskBoxInfo, new RecordItemIndex(9));
            repo.GenesisAutomation.TextMaskBox.PressKeys("bb");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'ott' with focus on 'GenesisAutomation.TextMaskBox'.", repo.GenesisAutomation.TextMaskBoxInfo, new RecordItemIndex(10));
            repo.GenesisAutomation.TextMaskBox.PressKeys("ott");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence ' ' with focus on 'GenesisAutomation.TextMaskBox'.", repo.GenesisAutomation.TextMaskBoxInfo, new RecordItemIndex(11));
            repo.GenesisAutomation.TextMaskBox.PressKeys(" ");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'GenesisAutomation.SearchEditLookUpPopup.GridControl' at 542;69.", repo.GenesisAutomation.SearchEditLookUpPopup.GridControlInfo, new RecordItemIndex(12));
            repo.GenesisAutomation.SearchEditLookUpPopup.GridControl.Click("542;69");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'PurchaseOrder.WpItem.TextMaskBox1' at 233;5.", repo.PurchaseOrder.WpItem.TextMaskBox1Info, new RecordItemIndex(13));
            repo.PurchaseOrder.WpItem.TextMaskBox1.Click("233;5");
            Delay.Milliseconds(200);
            
            NewVariable = ValueConverter.ToString(Random());
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$NewVariable' with focus on 'PurchaseOrder.WpItem.TextMaskBox1'.", repo.PurchaseOrder.WpItem.TextMaskBox1Info, new RecordItemIndex(15));
            repo.PurchaseOrder.WpItem.TextMaskBox1.PressKeys(NewVariable);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'PurchaseOrder.WpItem.TextMaskBox2' at 442;17.", repo.PurchaseOrder.WpItem.TextMaskBox2Info, new RecordItemIndex(16));
            repo.PurchaseOrder.WpItem.TextMaskBox2.Click("442;17");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'test' with focus on 'PurchaseOrder.WpItem.TextMaskBox2'.", repo.PurchaseOrder.WpItem.TextMaskBox2Info, new RecordItemIndex(17));
            repo.PurchaseOrder.WpItem.TextMaskBox2.PressKeys("test");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence ' kit' with focus on 'PurchaseOrder.WpItem.TextMaskBox2'.", repo.PurchaseOrder.WpItem.TextMaskBox2Info, new RecordItemIndex(18));
            repo.PurchaseOrder.WpItem.TextMaskBox2.PressKeys(" kit");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Down}' with focus on 'PurchaseOrder.WpItem.TextMaskBox2'.", repo.PurchaseOrder.WpItem.TextMaskBox2Info, new RecordItemIndex(19));
            repo.PurchaseOrder.WpItem.TextMaskBox2.PressKeys("{Down}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Return}' with focus on 'PurchaseOrder.WpItem.TextMaskBox2'.", repo.PurchaseOrder.WpItem.TextMaskBox2Info, new RecordItemIndex(20));
            repo.PurchaseOrder.WpItem.TextMaskBox2.PressKeys("{Return}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'PurchaseOrder.WpItem.TxtDescription' at 375;179.", repo.PurchaseOrder.WpItem.TxtDescriptionInfo, new RecordItemIndex(21));
            repo.PurchaseOrder.WpItem.TxtDescription.Click("375;179");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'PurchaseOrder.WpItem.TsPassthrough' at 205;-113.", repo.PurchaseOrder.WpItem.TsPassthroughInfo, new RecordItemIndex(22));
            repo.PurchaseOrder.WpItem.TsPassthrough.Click("205;-113");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'GenesisAutomation.SearchEditLookUpPopup.LabelControl1' at 228;61.", repo.GenesisAutomation.SearchEditLookUpPopup.LabelControl1Info, new RecordItemIndex(23));
            repo.GenesisAutomation.SearchEditLookUpPopup.LabelControl1.Click("228;61");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'PurchaseOrder.WpItem.DdlItemStatus' at 305;16.", repo.PurchaseOrder.WpItem.DdlItemStatusInfo, new RecordItemIndex(24));
            repo.PurchaseOrder.WpItem.DdlItemStatus.Click("305;16");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'GenesisAutomation.SearchEditLookUpPopup.GridControl' at 476;36.", repo.GenesisAutomation.SearchEditLookUpPopup.GridControlInfo, new RecordItemIndex(25));
            repo.GenesisAutomation.SearchEditLookUpPopup.GridControl.Click("476;36");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'PurchaseOrder.WpItem.DdlItemCategory' at 376;16.", repo.PurchaseOrder.WpItem.DdlItemCategoryInfo, new RecordItemIndex(26));
            repo.PurchaseOrder.WpItem.DdlItemCategory.Click("376;16");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'GenesisAutomation.SearchEditLookUpPopup.GridControl' at 354;36.", repo.GenesisAutomation.SearchEditLookUpPopup.GridControlInfo, new RecordItemIndex(27));
            repo.GenesisAutomation.SearchEditLookUpPopup.GridControl.Click("354;36");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'PurchaseOrder.WpItem.DdlItemBodySide' at 303;17.", repo.PurchaseOrder.WpItem.DdlItemBodySideInfo, new RecordItemIndex(28));
            repo.PurchaseOrder.WpItem.DdlItemBodySide.Click("303;17");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'GenesisAutomation.SearchEditLookUpPopup.GridControl' at 436;42.", repo.GenesisAutomation.SearchEditLookUpPopup.GridControlInfo, new RecordItemIndex(29));
            repo.GenesisAutomation.SearchEditLookUpPopup.GridControl.Click("436;42");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'PurchaseOrder.WpItem.DdlItemBodySite' at 376;16.", repo.PurchaseOrder.WpItem.DdlItemBodySiteInfo, new RecordItemIndex(30));
            repo.PurchaseOrder.WpItem.DdlItemBodySite.Click("376;16");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'GenesisAutomation.SearchEditLookUpPopup.GridControl' at 471;246.", repo.GenesisAutomation.SearchEditLookUpPopup.GridControlInfo, new RecordItemIndex(31));
            repo.GenesisAutomation.SearchEditLookUpPopup.GridControl.Click("471;246");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'PurchaseOrder.WpItem.DdlAccountCode' at 310;20.", repo.PurchaseOrder.WpItem.DdlAccountCodeInfo, new RecordItemIndex(32));
            repo.PurchaseOrder.WpItem.DdlAccountCode.Click("310;20");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'GenesisAutomation.SearchEditLookUpPopup.DescriptionRow3' at 247;-10.", repo.GenesisAutomation.SearchEditLookUpPopup.DescriptionRow3Info, new RecordItemIndex(33));
            repo.GenesisAutomation.SearchEditLookUpPopup.DescriptionRow3.Click("247;-10");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'PurchaseOrder.WpItem.TsPassthrough' at 310;56.", repo.PurchaseOrder.WpItem.TsPassthroughInfo, new RecordItemIndex(34));
            repo.PurchaseOrder.WpItem.TsPassthrough.Click("310;56");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'GenesisAutomation.SearchEditLookUpPopup.DescriptionRow3' at 307;19.", repo.GenesisAutomation.SearchEditLookUpPopup.DescriptionRow3Info, new RecordItemIndex(35));
            repo.GenesisAutomation.SearchEditLookUpPopup.DescriptionRow3.Click("307;19");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'PurchaseOrder.WpItem.TextBoxMaskBox' at 239;8.", repo.PurchaseOrder.WpItem.TextBoxMaskBoxInfo, new RecordItemIndex(36));
            repo.PurchaseOrder.WpItem.TextBoxMaskBox.Click("239;8");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Back}' with focus on 'PurchaseOrder.WpItem.TextBoxMaskBox'.", repo.PurchaseOrder.WpItem.TextBoxMaskBoxInfo, new RecordItemIndex(37));
            repo.PurchaseOrder.WpItem.TextBoxMaskBox.PressKeys("{Back}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Back}' with focus on 'PurchaseOrder.WpItem.TextBoxMaskBox'.", repo.PurchaseOrder.WpItem.TextBoxMaskBoxInfo, new RecordItemIndex(38));
            repo.PurchaseOrder.WpItem.TextBoxMaskBox.PressKeys("{Back}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{NumPad4}' with focus on 'PurchaseOrder.WpItem.TextBoxMaskBox'.", repo.PurchaseOrder.WpItem.TextBoxMaskBoxInfo, new RecordItemIndex(39));
            repo.PurchaseOrder.WpItem.TextBoxMaskBox.PressKeys("{NumPad4}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'PurchaseOrder.BtnNext' at 62;16.", repo.PurchaseOrder.BtnNextInfo, new RecordItemIndex(40));
            repo.PurchaseOrder.BtnNext.Click("62;16");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'PurchaseOrder.BtnNext' at 62;16.", repo.PurchaseOrder.BtnNextInfo, new RecordItemIndex(41));
            repo.PurchaseOrder.BtnNext.Click("62;16");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'PurchaseOrder' at 1211;18.", repo.PurchaseOrder.SelfInfo, new RecordItemIndex(42));
            repo.PurchaseOrder.Self.Click("1211;18");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 2s.", new RecordItemIndex(43));
            Delay.Duration(2000, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'PurchaseOrder.UcStep3LocationProfile.ReorderQuantityRow2' at 29;13.", repo.PurchaseOrder.UcStep3LocationProfile.ReorderQuantityRow2Info, new RecordItemIndex(44));
            repo.PurchaseOrder.UcStep3LocationProfile.ReorderQuantityRow2.Click("29;13");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'GenesisAutomation.SearchEditLookUpPopup.GridControl' at 376;201.", repo.GenesisAutomation.SearchEditLookUpPopup.GridControlInfo, new RecordItemIndex(45));
            repo.GenesisAutomation.SearchEditLookUpPopup.GridControl.Click("376;201");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 1s.", new RecordItemIndex(46));
            Delay.Duration(1000, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Down item 'PurchaseOrder.UcStep3LocationProfile.SelectionRow2' at 57;10.", repo.PurchaseOrder.UcStep3LocationProfile.SelectionRow2Info, new RecordItemIndex(47));
            repo.PurchaseOrder.UcStep3LocationProfile.SelectionRow2.MoveTo("57;10");
            Mouse.ButtonDown(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FrmCreateItemWizard.BtnNext' at LowerRight.", repo.FrmCreateItemWizard.BtnNextInfo, new RecordItemIndex(48));
            repo.FrmCreateItemWizard.BtnNext.Click(Location.LowerRight);
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left DoubleClick item 'FrmCreateItemWizard.BtnFinish' at LowerRight.", repo.FrmCreateItemWizard.BtnFinishInfo, new RecordItemIndex(49));
            repo.FrmCreateItemWizard.BtnFinish.DoubleClick(Location.LowerRight);
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 5s.", new RecordItemIndex(50));
            Delay.Duration(5000, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'PurchaseOrder.SimpleButton1' at Center.", repo.PurchaseOrder.SimpleButton1Info, new RecordItemIndex(51));
            repo.PurchaseOrder.SimpleButton1.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'PurchaseOrder.SimpleButton1'.", repo.PurchaseOrder.SimpleButton1Info, new RecordItemIndex(52));
            Validate.Exists(repo.PurchaseOrder.SimpleButton1Info);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Success, "User", "", new RecordItemIndex(53));
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
