///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace Genesis.Desktop
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the Genesis_DesktopRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("4c050442-7a9f-46bf-bfaf-2c1b4f0c601f")]
    public partial class Genesis_DesktopRepository : RepoGenBaseFolder
    {
        static Genesis_DesktopRepository instance = new Genesis_DesktopRepository();

        /// <summary>
        /// Gets the singleton class instance representing the Genesis_DesktopRepository element repository.
        /// </summary>
        [RepositoryFolder("4c050442-7a9f-46bf-bfaf-2c1b4f0c601f")]
        public static Genesis_DesktopRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public Genesis_DesktopRepository() 
            : base("Genesis_DesktopRepository", "/", null, 0, false, "4c050442-7a9f-46bf-bfaf-2c1b4f0c601f", ".\\RepositoryImages\\Genesis_DesktopRepository4c050442.rximgres")
        {
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("4c050442-7a9f-46bf-bfaf-2c1b4f0c601f")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class Genesis_DesktopRepositoryFolders
    {
    }
#pragma warning restore 0436
}
