///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace Genesis.Desktop.Recordings.Inventory
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The GoodsReceiptRecalled recording.
    /// </summary>
    [TestModule("9cd1b813-9158-44a8-a6ac-9c18607661fd", ModuleType.Recording, 1)]
    public partial class GoodsReceiptRecalled : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::Genesis.Desktop.Genesis_DesktopRepository repository.
        /// </summary>
        public static global::Genesis.Desktop.Genesis_DesktopRepository repo = global::Genesis.Desktop.Genesis_DesktopRepository.Instance;

        static GoodsReceiptRecalled instance = new GoodsReceiptRecalled();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public GoodsReceiptRecalled()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static GoodsReceiptRecalled Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FrmMain.CreateRequisition' at 46;24.", repo.FrmMain.CreateRequisitionInfo, new RecordItemIndex(0));
            repo.FrmMain.CreateRequisition.Click("46;24");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FrmCreateRequisition.Open' at 10;10.", repo.FrmCreateRequisition.OpenInfo, new RecordItemIndex(1));
            repo.FrmCreateRequisition.Open.Click("10;10");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'GenesisAutomation.Row2' at 9;9.", repo.GenesisAutomation.Row2Info, new RecordItemIndex(2));
            repo.GenesisAutomation.Row2.Click("9;9");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FrmCreateRequisition.Open1' at 7;13.", repo.FrmCreateRequisition.Open1Info, new RecordItemIndex(3));
            repo.FrmCreateRequisition.Open1.Click("7;13");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'GenesisAutomation.TextMaskBox' at 138;8.", repo.GenesisAutomation.TextMaskBoxInfo, new RecordItemIndex(4));
            repo.GenesisAutomation.TextMaskBox.Click("138;8");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'ahb' with focus on 'GenesisAutomation.TextMaskBox'.", repo.GenesisAutomation.TextMaskBoxInfo, new RecordItemIndex(5));
            repo.GenesisAutomation.TextMaskBox.PressKeys("ahb");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '822' with focus on 'GenesisAutomation.TextMaskBox'.", repo.GenesisAutomation.TextMaskBoxInfo, new RecordItemIndex(6));
            repo.GenesisAutomation.TextMaskBox.PressKeys("822");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'GenesisAutomation.Row1' at 10;11.", repo.GenesisAutomation.Row1Info, new RecordItemIndex(7));
            repo.GenesisAutomation.Row1.Click("10;11");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FrmCreateRequisition.AddRequisition' at 84;7.", repo.FrmCreateRequisition.AddRequisitionInfo, new RecordItemIndex(8));
            repo.FrmCreateRequisition.AddRequisition.Click("84;7");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FrmCreateRequisition.Confirm' at 99;12.", repo.FrmCreateRequisition.ConfirmInfo, new RecordItemIndex(9));
            repo.FrmCreateRequisition.Confirm.Click("99;12");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'GenesisAutomation1.ButtonOK' at 42;14.", repo.GenesisAutomation1.ButtonOKInfo, new RecordItemIndex(10));
            repo.GenesisAutomation1.ButtonOK.Click("42;14");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FrmMain.NewOrders' at 49;14.", repo.FrmMain.NewOrdersInfo, new RecordItemIndex(11));
            repo.FrmMain.NewOrders.Click("49;14");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FrmMain.ReleaseRow0' at 28;10.", repo.FrmMain.ReleaseRow0Info, new RecordItemIndex(12));
            repo.FrmMain.ReleaseRow0.Click("28;10");
            Delay.Milliseconds(0);
            
            try {
                Report.Log(ReportLevel.Info, "Mouse", "(Optional Action)\r\nMouse Left Click item 'PurchaseOrder.ButtonOK' at 38;10.", repo.PurchaseOrder.ButtonOKInfo, new RecordItemIndex(13));
                repo.PurchaseOrder.ButtonOK.Click("38;10");
                Delay.Milliseconds(0);
            } catch(Exception ex) { Report.Log(ReportLevel.Warn, "Module", "(Optional Action) " + ex.Message, new RecordItemIndex(13)); }
            
            try {
                Report.Log(ReportLevel.Info, "Mouse", "(Optional Action)\r\nMouse Left Click item 'GenesisAutomation1.ButtonYes' at 39;9.", repo.GenesisAutomation1.ButtonYesInfo, new RecordItemIndex(14));
                repo.GenesisAutomation1.ButtonYes.Click("39;9");
                Delay.Milliseconds(0);
            } catch(Exception ex) { Report.Log(ReportLevel.Warn, "Module", "(Optional Action) " + ex.Message, new RecordItemIndex(14)); }
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FrmMain.SplitControl.OutstandingOrders' at 69;13.", repo.FrmMain.SplitControl.OutstandingOrdersInfo, new RecordItemIndex(15));
            repo.FrmMain.SplitControl.OutstandingOrders.Click("69;13");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 2s.", new RecordItemIndex(16));
            Delay.Duration(2000, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FrmMain.SplitControl.GoodsReceiptRow0' at 26;14.", repo.FrmMain.SplitControl.GoodsReceiptRow0Info, new RecordItemIndex(17));
            repo.FrmMain.SplitControl.GoodsReceiptRow0.Click("26;14");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'PurchaseOrder.ReceiptRow0' at 24;14.", repo.PurchaseOrder.ReceiptRow0Info, new RecordItemIndex(18));
            repo.PurchaseOrder.ReceiptRow0.Click("24;14");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'PurchaseOrder.TextMaskBox1' at 34;8.", repo.PurchaseOrder.TextMaskBox1Info, new RecordItemIndex(19));
            repo.PurchaseOrder.TextMaskBox1.Click("34;8");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '222' with focus on 'PurchaseOrder.TextMaskBox1'.", repo.PurchaseOrder.TextMaskBox1Info, new RecordItemIndex(20));
            repo.PurchaseOrder.TextMaskBox1.PressKeys("222");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'PurchaseOrder.TextMaskBox' at 55;5.", repo.PurchaseOrder.TextMaskBoxInfo, new RecordItemIndex(21));
            repo.PurchaseOrder.TextMaskBox.Click("55;5");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'recalled' with focus on 'PurchaseOrder.TextMaskBox'.", repo.PurchaseOrder.TextMaskBoxInfo, new RecordItemIndex(22));
            repo.PurchaseOrder.TextMaskBox.PressKeys("recalled");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence ' item' with focus on 'PurchaseOrder.TextMaskBox'.", repo.PurchaseOrder.TextMaskBoxInfo, new RecordItemIndex(23));
            repo.PurchaseOrder.TextMaskBox.PressKeys(" item");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'PurchaseOrder.Receive' at 110;18.", repo.PurchaseOrder.ReceiveInfo, new RecordItemIndex(24));
            repo.PurchaseOrder.Receive.Click("110;18");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'GenesisAutomation1.ButtonYes'.", repo.GenesisAutomation1.ButtonYesInfo, new RecordItemIndex(25));
            Validate.Exists(repo.GenesisAutomation1.ButtonYesInfo);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'GenesisAutomation1.ButtonYes' at 34;10.", repo.GenesisAutomation1.ButtonYesInfo, new RecordItemIndex(26));
            repo.GenesisAutomation1.ButtonYes.Click("34;10");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'GenesisAutomation1.ButtonNo' at 43;14.", repo.GenesisAutomation1.ButtonNoInfo, new RecordItemIndex(27));
            repo.GenesisAutomation1.ButtonNo.Click("43;14");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'PurchaseOrder.CloseWindow1' at 79;12.", repo.PurchaseOrder.CloseWindow1Info, new RecordItemIndex(28));
            repo.PurchaseOrder.CloseWindow1.Click("79;12");
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
