///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace Genesis.Desktop.Recordings.Inventory
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The GoodsReceiptSameItemLotDifferentSupplier recording.
    /// </summary>
    [TestModule("d6b3848f-774f-4f2a-a1b0-46db82deb0dd", ModuleType.Recording, 1)]
    public partial class GoodsReceiptSameItemLotDifferentSupplier : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::Genesis.Desktop.Genesis_DesktopRepository repository.
        /// </summary>
        public static global::Genesis.Desktop.Genesis_DesktopRepository repo = global::Genesis.Desktop.Genesis_DesktopRepository.Instance;

        static GoodsReceiptSameItemLotDifferentSupplier instance = new GoodsReceiptSameItemLotDifferentSupplier();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public GoodsReceiptSameItemLotDifferentSupplier()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static GoodsReceiptSameItemLotDifferentSupplier Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FrmMain.CreateRequisition' at 46;21.", repo.FrmMain.CreateRequisitionInfo, new RecordItemIndex(0));
            repo.FrmMain.CreateRequisition.Click("46;21");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FrmCreateRequisition.Open' at 5;10.", repo.FrmCreateRequisition.OpenInfo, new RecordItemIndex(1));
            repo.FrmCreateRequisition.Open.Click("5;10");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'GenesisAutomation.Row1' at 8;9.", repo.GenesisAutomation.Row1Info, new RecordItemIndex(2));
            repo.GenesisAutomation.Row1.Click("8;9");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FrmCreateRequisition.Open1' at 7;16.", repo.FrmCreateRequisition.Open1Info, new RecordItemIndex(3));
            repo.FrmCreateRequisition.Open1.Click("7;16");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'GenesisAutomation.TextMaskBox' at 125;9.", repo.GenesisAutomation.TextMaskBoxInfo, new RecordItemIndex(4));
            repo.GenesisAutomation.TextMaskBox.Click("125;9");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'fbe' with focus on 'GenesisAutomation.TextMaskBox'.", repo.GenesisAutomation.TextMaskBoxInfo, new RecordItemIndex(5));
            repo.GenesisAutomation.TextMaskBox.PressKeys("fbe");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '23' with focus on 'GenesisAutomation.TextMaskBox'.", repo.GenesisAutomation.TextMaskBoxInfo, new RecordItemIndex(6));
            repo.GenesisAutomation.TextMaskBox.PressKeys("23");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '633' with focus on 'GenesisAutomation.TextMaskBox'.", repo.GenesisAutomation.TextMaskBoxInfo, new RecordItemIndex(7));
            repo.GenesisAutomation.TextMaskBox.PressKeys("633");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'GenesisAutomation.Row1' at 7;10.", repo.GenesisAutomation.Row1Info, new RecordItemIndex(8));
            repo.GenesisAutomation.Row1.Click("7;10");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FrmCreateRequisition.Open2' at 8;11.", repo.FrmCreateRequisition.Open2Info, new RecordItemIndex(9));
            repo.FrmCreateRequisition.Open2.Click("8;11");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'GenesisAutomation.Row2' at 4;11.", repo.GenesisAutomation.Row2Info, new RecordItemIndex(10));
            repo.GenesisAutomation.Row2.Click("4;11");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FrmCreateRequisition.AddRequisition' at 85;18.", repo.FrmCreateRequisition.AddRequisitionInfo, new RecordItemIndex(11));
            repo.FrmCreateRequisition.AddRequisition.Click("85;18");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FrmCreateRequisition.Confirm' at 92;17.", repo.FrmCreateRequisition.ConfirmInfo, new RecordItemIndex(12));
            repo.FrmCreateRequisition.Confirm.Click("92;17");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'GenesisAutomation1.ButtonOK' at 44;10.", repo.GenesisAutomation1.ButtonOKInfo, new RecordItemIndex(13));
            repo.GenesisAutomation1.ButtonOK.Click("44;10");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FrmMain.NewOrders' at 56;14.", repo.FrmMain.NewOrdersInfo, new RecordItemIndex(14));
            repo.FrmMain.NewOrders.Click("56;14");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FrmMain.ReleaseRow0' at 32;15.", repo.FrmMain.ReleaseRow0Info, new RecordItemIndex(15));
            repo.FrmMain.ReleaseRow0.Click("32;15");
            Delay.Milliseconds(0);
            
            try {
                Report.Log(ReportLevel.Info, "Mouse", "(Optional Action)\r\nMouse Left Click item 'PurchaseOrder.ButtonOK' at 34;6.", repo.PurchaseOrder.ButtonOKInfo, new RecordItemIndex(16));
                repo.PurchaseOrder.ButtonOK.Click("34;6");
                Delay.Milliseconds(0);
            } catch(Exception ex) { Report.Log(ReportLevel.Warn, "Module", "(Optional Action) " + ex.Message, new RecordItemIndex(16)); }
            
            try {
                Report.Log(ReportLevel.Info, "Mouse", "(Optional Action)\r\nMouse Left Click item 'GenesisAutomation1.ButtonYes' at 34;6.", repo.GenesisAutomation1.ButtonYesInfo, new RecordItemIndex(17));
                repo.GenesisAutomation1.ButtonYes.Click("34;6");
                Delay.Milliseconds(0);
            } catch(Exception ex) { Report.Log(ReportLevel.Warn, "Module", "(Optional Action) " + ex.Message, new RecordItemIndex(17)); }
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FrmMain.SplitControl.OutstandingOrders' at 97;12.", repo.FrmMain.SplitControl.OutstandingOrdersInfo, new RecordItemIndex(18));
            repo.FrmMain.SplitControl.OutstandingOrders.Click("97;12");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FrmMain.SplitControl.GoodsReceiptRow0' at 29;11.", repo.FrmMain.SplitControl.GoodsReceiptRow0Info, new RecordItemIndex(19));
            repo.FrmMain.SplitControl.GoodsReceiptRow0.Click("29;11");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'PurchaseOrder.ReceiptRow0' at 30;10.", repo.PurchaseOrder.ReceiptRow0Info, new RecordItemIndex(20));
            repo.PurchaseOrder.ReceiptRow0.Click("30;10");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'PurchaseOrder.TextMaskBox1' at 41;7.", repo.PurchaseOrder.TextMaskBox1Info, new RecordItemIndex(21));
            repo.PurchaseOrder.TextMaskBox1.Click("41;7");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '312' with focus on 'PurchaseOrder.TextMaskBox1'.", repo.PurchaseOrder.TextMaskBox1Info, new RecordItemIndex(22));
            repo.PurchaseOrder.TextMaskBox1.PressKeys("312");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'PurchaseOrder.TextMaskBox' at 166;11.", repo.PurchaseOrder.TextMaskBoxInfo, new RecordItemIndex(23));
            repo.PurchaseOrder.TextMaskBox.Click("166;11");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'same item same' with focus on 'PurchaseOrder.TextMaskBox'.", repo.PurchaseOrder.TextMaskBoxInfo, new RecordItemIndex(24));
            repo.PurchaseOrder.TextMaskBox.PressKeys("same item same");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence ' lot different supplier' with focus on 'PurchaseOrder.TextMaskBox'.", repo.PurchaseOrder.TextMaskBoxInfo, new RecordItemIndex(25));
            repo.PurchaseOrder.TextMaskBox.PressKeys(" lot different supplier");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'PurchaseOrder.Receive' at 90;22.", repo.PurchaseOrder.ReceiveInfo, new RecordItemIndex(26));
            repo.PurchaseOrder.Receive.Click("90;22");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'GenesisAutomation1.ButtonNo' at 38;7.", repo.GenesisAutomation1.ButtonNoInfo, new RecordItemIndex(27));
            repo.GenesisAutomation1.ButtonNo.Click("38;7");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'PurchaseOrder.CloseWindow1' at 98;16.", repo.PurchaseOrder.CloseWindow1Info, new RecordItemIndex(28));
            repo.PurchaseOrder.CloseWindow1.Click("98;16");
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
