///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace Genesis.Desktop.Recordings.General
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The Login recording.
    /// </summary>
    [TestModule("2271998a-409b-49c5-887a-56df0dc0a1a0", ModuleType.Recording, 1)]
    public partial class Login : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::Genesis.Desktop.Genesis_DesktopRepository repository.
        /// </summary>
        public static global::Genesis.Desktop.Genesis_DesktopRepository repo = global::Genesis.Desktop.Genesis_DesktopRepository.Instance;

        static Login instance = new Login();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Login()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Login Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Application", "Run application 'C:\\Program Files (x86)\\Genesis Automation Ltd\\Genesis Automation\\GenesisAutomation.exe' in normal mode. Return value bound to $.", new RecordItemIndex(0));
            Host.Local.RunApplication("C:\\Program Files (x86)\\Genesis Automation Ltd\\Genesis Automation\\GenesisAutomation.exe", "", "C:\\Program Files (x86)\\Genesis Automation Ltd\\Genesis Automation", false);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FrmLogin.TextMaskBox' at 142;3.", repo.FrmLogin.TextMaskBoxInfo, new RecordItemIndex(1));
            repo.FrmLogin.TextMaskBox.Click("142;3");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Back}{Back}{Back}{Back}{Back}{Back}{Back}{Back}{Back}{Back}{Back}' with focus on 'FrmLogin.TextMaskBox'.", repo.FrmLogin.TextMaskBoxInfo, new RecordItemIndex(2));
            repo.FrmLogin.TextMaskBox.PressKeys("{Back}{Back}{Back}{Back}{Back}{Back}{Back}{Back}{Back}{Back}{Back}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'system' with focus on 'FrmLogin.TextMaskBox'.", repo.FrmLogin.TextMaskBoxInfo, new RecordItemIndex(3));
            repo.FrmLogin.TextMaskBox.PressKeys("system");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FrmLogin.NoCapsMsgTextBoxMaskBox' at 149;8.", repo.FrmLogin.NoCapsMsgTextBoxMaskBoxInfo, new RecordItemIndex(4));
            repo.FrmLogin.NoCapsMsgTextBoxMaskBox.Click("149;8");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'password1' with focus on 'FrmLogin.NoCapsMsgTextBoxMaskBox'.", repo.FrmLogin.NoCapsMsgTextBoxMaskBoxInfo, new RecordItemIndex(5));
            repo.FrmLogin.NoCapsMsgTextBoxMaskBox.PressKeys("password1");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FrmLogin.SignIn' at 60;7.", repo.FrmLogin.SignInInfo, new RecordItemIndex(6));
            repo.FrmLogin.SignIn.Click("60;7");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 5s.", new RecordItemIndex(7));
            Delay.Duration(5000, false);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'FrmMain'.", repo.FrmMain.SelfInfo, new RecordItemIndex(8));
            Validate.Exists(repo.FrmMain.SelfInfo);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Success, "User", "", new RecordItemIndex(9));
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
