///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace Genesis.Desktop.TestSuite.MasterData.Recordings
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The CreateNewItemWizardConsumables recording.
    /// </summary>
    [TestModule("a416a480-b4ad-4395-bbce-9a8ae729c271", ModuleType.Recording, 1)]
    public partial class CreateNewItemWizardConsumables : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::Genesis.Desktop.TestSuite.MasterData.Genesis_Desktop_TestSuite_MasterDataRepository repository.
        /// </summary>
        public static global::Genesis.Desktop.TestSuite.MasterData.Genesis_Desktop_TestSuite_MasterDataRepository repo = global::Genesis.Desktop.TestSuite.MasterData.Genesis_Desktop_TestSuite_MasterDataRepository.Instance;

        static CreateNewItemWizardConsumables instance = new CreateNewItemWizardConsumables();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public CreateNewItemWizardConsumables()
        {
            NewVariable = "1234587";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static CreateNewItemWizardConsumables Instance
        {
            get { return instance; }
        }

#region Variables

        string _NewVariable;

        /// <summary>
        /// Gets or sets the value of variable NewVariable.
        /// </summary>
        [TestVariable("e5d2bbdb-60b9-4fb3-a7a1-6c68cc52ba3b")]
        public string NewVariable
        {
            get { return _NewVariable; }
            set { _NewVariable = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FrmMain.MasterData' at 12;17.", repo.FrmMain.MasterDataInfo, new RecordItemIndex(0));
            repo.FrmMain.MasterData.Click("12;17");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'GenesisAutomation1.NewItemWizard' at 47;56.", repo.GenesisAutomation1.NewItemWizardInfo, new RecordItemIndex(1));
            repo.GenesisAutomation1.NewItemWizard.Click("47;56");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'PurchaseOrder.BtnNext' at 51;19.", repo.PurchaseOrder.BtnNextInfo, new RecordItemIndex(2));
            repo.PurchaseOrder.BtnNext.Click("51;19");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Wait", "Waiting 5s to exist. Associated repository item: 'PurchaseOrder.UcStep1Item.TextSelectSupplier'", repo.PurchaseOrder.UcStep1Item.TextSelectSupplierInfo, new ActionTimeout(5000), new RecordItemIndex(3));
            repo.PurchaseOrder.UcStep1Item.TextSelectSupplierInfo.WaitForExists(5000);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'PurchaseOrder.UcStep1Item.TextSelectSupplier' at 212;9.", repo.PurchaseOrder.UcStep1Item.TextSelectSupplierInfo, new RecordItemIndex(4));
            repo.PurchaseOrder.UcStep1Item.TextSelectSupplier.Click("212;9");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'acutus' with focus on 'GenesisAutomation'.", repo.GenesisAutomation.SelfInfo, new RecordItemIndex(5));
            repo.GenesisAutomation.Self.EnsureVisible();
            Keyboard.Press("acutus", 100);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'GenesisAutomation.GridControl' at 420;32.", repo.GenesisAutomation.GridControlInfo, new RecordItemIndex(6));
            repo.GenesisAutomation.GridControl.Click("420;32");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'PurchaseOrder.UcStep1Item.TextMaskBox3' at 271;11.", repo.PurchaseOrder.UcStep1Item.TextMaskBox3Info, new RecordItemIndex(7));
            repo.PurchaseOrder.UcStep1Item.TextMaskBox3.Click("271;11");
            Delay.Milliseconds(200);
            
            NewVariable = ValueConverter.ToString(Random());
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$NewVariable' with focus on 'PurchaseOrder.UcStep1Item.TextMaskBox1'.", repo.PurchaseOrder.UcStep1Item.TextMaskBox1Info, new RecordItemIndex(9));
            repo.PurchaseOrder.UcStep1Item.TextMaskBox1.PressKeys(NewVariable, 100);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'PurchaseOrder.UcStep1Item.TextMaskBox4' at 260;8.", repo.PurchaseOrder.UcStep1Item.TextMaskBox4Info, new RecordItemIndex(10));
            repo.PurchaseOrder.UcStep1Item.TextMaskBox4.Click("260;8");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'test' with focus on 'PurchaseOrder.UcStep1Item.TextMaskBox4'.", repo.PurchaseOrder.UcStep1Item.TextMaskBox4Info, new RecordItemIndex(11));
            repo.PurchaseOrder.UcStep1Item.TextMaskBox4.PressKeys("test", 100);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'GenesisAutomation.TESTKIT' at 282;2.", repo.GenesisAutomation.TESTKITInfo, new RecordItemIndex(12));
            repo.GenesisAutomation.TESTKIT.Click("282;2");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'PurchaseOrder.UcStep1Item.TextSelectItemGroup' at 219;9.", repo.PurchaseOrder.UcStep1Item.TextSelectItemGroupInfo, new RecordItemIndex(13));
            repo.PurchaseOrder.UcStep1Item.TextSelectItemGroup.Click("219;9");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'AAA' with focus on 'GenesisAutomation'.", repo.GenesisAutomation.SelfInfo, new RecordItemIndex(14));
            repo.GenesisAutomation.Self.EnsureVisible();
            Keyboard.Press("AAA", 100);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'GenesisAutomation.DescriptionRow0' at 29;9.", repo.GenesisAutomation.DescriptionRow0Info, new RecordItemIndex(15));
            repo.GenesisAutomation.DescriptionRow0.Click("29;9");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'PurchaseOrder.UcStep1Item.Active' at 207;8.", repo.PurchaseOrder.UcStep1Item.ActiveInfo, new RecordItemIndex(16));
            repo.PurchaseOrder.UcStep1Item.Active.Click("207;8");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'GenesisAutomation.ContainerLc.CodeRow0' at 133;13.", repo.GenesisAutomation.ContainerLc.CodeRow0Info, new RecordItemIndex(17));
            repo.GenesisAutomation.ContainerLc.CodeRow0.Click("133;13");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'PurchaseOrder.UcStep1Item.TextSelectItemCategory' at 177;7.", repo.PurchaseOrder.UcStep1Item.TextSelectItemCategoryInfo, new RecordItemIndex(18));
            repo.PurchaseOrder.UcStep1Item.TextSelectItemCategory.Click("177;7");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'GenesisAutomation.ContainerLc.CodeRow1' at 49;10.", repo.GenesisAutomation.ContainerLc.CodeRow1Info, new RecordItemIndex(19));
            repo.GenesisAutomation.ContainerLc.CodeRow1.Click("49;10");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'PurchaseOrder.UcStep1Item.TextSelectAccountCode' at 191;8.", repo.PurchaseOrder.UcStep1Item.TextSelectAccountCodeInfo, new RecordItemIndex(20));
            repo.PurchaseOrder.UcStep1Item.TextSelectAccountCode.Click("191;8");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'GenesisAutomation.ContainerLc.DescriptionRow3' at 100;10.", repo.GenesisAutomation.ContainerLc.DescriptionRow3Info, new RecordItemIndex(21));
            repo.GenesisAutomation.ContainerLc.DescriptionRow3.Click("100;10");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'PurchaseOrder.UcStep1Item.TextBoxMaskBox1' at 211;9.", repo.PurchaseOrder.UcStep1Item.TextBoxMaskBox1Info, new RecordItemIndex(22));
            repo.PurchaseOrder.UcStep1Item.TextBoxMaskBox1.Click("211;9");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Back}' with focus on 'PurchaseOrder.UcStep1Item.TextBoxMaskBox1'.", repo.PurchaseOrder.UcStep1Item.TextBoxMaskBox1Info, new RecordItemIndex(23));
            repo.PurchaseOrder.UcStep1Item.TextBoxMaskBox1.PressKeys("{Back}", 100);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{NumPad1}' with focus on 'PurchaseOrder.UcStep1Item.TextBoxMaskBox1'.", repo.PurchaseOrder.UcStep1Item.TextBoxMaskBox1Info, new RecordItemIndex(24));
            repo.PurchaseOrder.UcStep1Item.TextBoxMaskBox1.PressKeys("{NumPad1}", 100);
            Delay.Milliseconds(0);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'PurchaseOrder.UcStep1Item.DdlItemGroup' at 307;11.", repo.PurchaseOrder.UcStep1Item.DdlItemGroupInfo, new RecordItemIndex(25));
            //repo.PurchaseOrder.UcStep1Item.DdlItemGroup.Click("307;11");
            //Delay.Milliseconds(200);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'GenesisAutomation.GridControl' at 421;31.", repo.GenesisAutomation.GridControlInfo, new RecordItemIndex(26));
            //repo.GenesisAutomation.GridControl.Click("421;31");
            //Delay.Milliseconds(200);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'PurchaseOrder.UcStep1Item.DdlItemStatus' at 310;14.", repo.PurchaseOrder.UcStep1Item.DdlItemStatusInfo, new RecordItemIndex(27));
            //repo.PurchaseOrder.UcStep1Item.DdlItemStatus.Click("310;14");
            //Delay.Milliseconds(200);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'GenesisAutomation.GridControl' at 505;41.", repo.GenesisAutomation.GridControlInfo, new RecordItemIndex(28));
            //repo.GenesisAutomation.GridControl.Click("505;41");
            //Delay.Milliseconds(200);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'PurchaseOrder.UcStep1Item.DdlItemCategory' at 370;13.", repo.PurchaseOrder.UcStep1Item.DdlItemCategoryInfo, new RecordItemIndex(29));
            //repo.PurchaseOrder.UcStep1Item.DdlItemCategory.Click("370;13");
            //Delay.Milliseconds(200);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'GenesisAutomation.GridControl' at 461;63.", repo.GenesisAutomation.GridControlInfo, new RecordItemIndex(30));
            //repo.GenesisAutomation.GridControl.Click("461;63");
            //Delay.Milliseconds(200);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'PurchaseOrder.UcStep1Item.DdlAccountCode' at 307;16.", repo.PurchaseOrder.UcStep1Item.DdlAccountCodeInfo, new RecordItemIndex(31));
            //repo.PurchaseOrder.UcStep1Item.DdlAccountCode.Click("307;16");
            //Delay.Milliseconds(200);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'GenesisAutomation.GridControl' at 512;114.", repo.GenesisAutomation.GridControlInfo, new RecordItemIndex(32));
            //repo.GenesisAutomation.GridControl.Click("512;114");
            //Delay.Milliseconds(200);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'PurchaseOrder.UcStep1Item.TextBoxMaskBox1' at 265;10.", repo.PurchaseOrder.UcStep1Item.TextBoxMaskBox1Info, new RecordItemIndex(33));
            //repo.PurchaseOrder.UcStep1Item.TextBoxMaskBox1.Click("265;10");
            //Delay.Milliseconds(200);
            
            //Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{NumPad2}' with focus on 'PurchaseOrder.UcStep1Item.TextBoxMaskBox1'.", repo.PurchaseOrder.UcStep1Item.TextBoxMaskBox1Info, new RecordItemIndex(34));
            //repo.PurchaseOrder.UcStep1Item.TextBoxMaskBox1.PressKeys("{NumPad2}", 100);
            //Delay.Milliseconds(0);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'GenesisAutomation.GridControl' at 463;117.", repo.GenesisAutomation.GridControlInfo, new RecordItemIndex(35));
            //repo.GenesisAutomation.GridControl.Click("463;117");
            //Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'PurchaseOrder.BtnNext' at 31;6.", repo.PurchaseOrder.BtnNextInfo, new RecordItemIndex(36));
            repo.PurchaseOrder.BtnNext.Click("31;6");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'PurchaseOrder.BtnNext' at 33;9.", repo.PurchaseOrder.BtnNextInfo, new RecordItemIndex(37));
            repo.PurchaseOrder.BtnNext.Click("33;9");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'PurchaseOrder.Maximise' at 3;8.", repo.PurchaseOrder.MaximiseInfo, new RecordItemIndex(38));
            repo.PurchaseOrder.Maximise.Click("3;8");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'PurchaseOrder.WpLocationProfile.ReplenishFromRow0' at 50;13.", repo.PurchaseOrder.WpLocationProfile.ReplenishFromRow0Info, new RecordItemIndex(39));
            repo.PurchaseOrder.WpLocationProfile.ReplenishFromRow0.Click("50;13");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'PurchaseOrder.WpLocationProfile.ReplenishFromRow0' at 32;16.", repo.PurchaseOrder.WpLocationProfile.ReplenishFromRow0Info, new RecordItemIndex(40));
            repo.PurchaseOrder.WpLocationProfile.ReplenishFromRow0.Click("32;16");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'GenesisAutomation.ContainerLc.ReplenishFromRow6' at 66;3.", repo.GenesisAutomation.ContainerLc.ReplenishFromRow6Info, new RecordItemIndex(41));
            repo.GenesisAutomation.ContainerLc.ReplenishFromRow6.Click("66;3");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left DoubleClick item 'PurchaseOrder.WpLocationProfile.SelectionRow0' at 38;15.", repo.PurchaseOrder.WpLocationProfile.SelectionRow0Info, new RecordItemIndex(42));
            repo.PurchaseOrder.WpLocationProfile.SelectionRow0.DoubleClick("38;15");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'PurchaseOrder.ButtonNext' at 49;12.", repo.PurchaseOrder.ButtonNextInfo, new RecordItemIndex(43));
            repo.PurchaseOrder.ButtonNext.Click("49;12");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'PurchaseOrder.ButtonCreate' at 43;10.", repo.PurchaseOrder.ButtonCreateInfo, new RecordItemIndex(44));
            repo.PurchaseOrder.ButtonCreate.Click("43;10");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'GenesisAutomation1.ButtonOK' at 37;12.", repo.GenesisAutomation1.ButtonOKInfo, new RecordItemIndex(45));
            repo.GenesisAutomation1.ButtonOK.Click("37;12");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FrmMain1.Items' at 31;36.", repo.FrmMain1.ItemsInfo, new RecordItemIndex(46));
            repo.FrmMain1.Items.Click("31;36");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'GenesisAutomation1.FrmItem1.TextAllItemGroups' at 203;8.", repo.GenesisAutomation1.FrmItem1.TextAllItemGroupsInfo, new RecordItemIndex(47));
            repo.GenesisAutomation1.FrmItem1.TextAllItemGroups.Click("203;8");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'aAA' with focus on 'GenesisAutomation'.", repo.GenesisAutomation.SelfInfo, new RecordItemIndex(48));
            repo.GenesisAutomation.Self.EnsureVisible();
            Keyboard.Press("aAA", 100);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'GenesisAutomation.Find' at 30;6.", repo.GenesisAutomation.FindInfo, new RecordItemIndex(49));
            repo.GenesisAutomation.Find.Click("30;6");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'GenesisAutomation.DescriptionRow0' at 117;11.", repo.GenesisAutomation.DescriptionRow0Info, new RecordItemIndex(50));
            repo.GenesisAutomation.DescriptionRow0.Click("117;11");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'GenesisAutomation1.FrmItem1.TextAllItemCategories' at 202;7.", repo.GenesisAutomation1.FrmItem1.TextAllItemCategoriesInfo, new RecordItemIndex(51));
            repo.GenesisAutomation1.FrmItem1.TextAllItemCategories.Click("202;7");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'GenesisAutomation.ContainerLc.CodeRow1' at 57;11.", repo.GenesisAutomation.ContainerLc.CodeRow1Info, new RecordItemIndex(52));
            repo.GenesisAutomation.ContainerLc.CodeRow1.Click("57;11");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FrmMain.TextBoxMaskBox' at 240;5.", repo.FrmMain.TextBoxMaskBoxInfo, new RecordItemIndex(53));
            repo.FrmMain.TextBoxMaskBox.Click("240;5");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$NewVariable' with focus on 'FrmMain.TextBoxMaskBox'.", repo.FrmMain.TextBoxMaskBoxInfo, new RecordItemIndex(54));
            repo.FrmMain.TextBoxMaskBox.PressKeys(NewVariable, 100);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'GenesisAutomation1.FrmItem1.Find' at Center.", repo.GenesisAutomation1.FrmItem1.FindInfo, new RecordItemIndex(55));
            repo.GenesisAutomation1.FrmItem1.Find.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeContains (Text>$NewVariable) on item 'GenesisAutomation1.FrmItem1.SupplierItemCodeRow0'.", repo.GenesisAutomation1.FrmItem1.SupplierItemCodeRow0Info, new RecordItemIndex(56));
            Validate.AttributeContains(repo.GenesisAutomation1.FrmItem1.SupplierItemCodeRow0Info, "Text", NewVariable);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'GenesisAutomation1.GenesisAutomation' at 133;15.", repo.GenesisAutomation1.GenesisAutomationInfo, new RecordItemIndex(57));
            repo.GenesisAutomation1.GenesisAutomation.Click("133;15");
            Delay.Milliseconds(200);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
