///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace Genesis.Desktop.TestSuite.MasterData.Recordings
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The CreateNewItemWizardImplants recording.
    /// </summary>
    [TestModule("5c2f2d82-9076-46ee-9c32-49e0221edcac", ModuleType.Recording, 1)]
    public partial class CreateNewItemWizardImplants : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::Genesis.Desktop.TestSuite.MasterData.Genesis_Desktop_TestSuite_MasterDataRepository repository.
        /// </summary>
        public static global::Genesis.Desktop.TestSuite.MasterData.Genesis_Desktop_TestSuite_MasterDataRepository repo = global::Genesis.Desktop.TestSuite.MasterData.Genesis_Desktop_TestSuite_MasterDataRepository.Instance;

        static CreateNewItemWizardImplants instance = new CreateNewItemWizardImplants();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public CreateNewItemWizardImplants()
        {
            NewVariable = "1234587";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static CreateNewItemWizardImplants Instance
        {
            get { return instance; }
        }

#region Variables

        string _NewVariable;

        /// <summary>
        /// Gets or sets the value of variable NewVariable.
        /// </summary>
        [TestVariable("be98b503-2da7-4ad9-bf63-925746e91ceb")]
        public string NewVariable
        {
            get { return _NewVariable; }
            set { _NewVariable = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Wait", "Waiting 5s to exist. Associated repository item: 'FrmMain1.MasterData'", repo.FrmMain1.MasterDataInfo, new ActionTimeout(5000), new RecordItemIndex(0));
            repo.FrmMain1.MasterDataInfo.WaitForExists(5000);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FrmMain1.MasterData' at 4;20.", repo.FrmMain1.MasterDataInfo, new RecordItemIndex(1));
            repo.FrmMain1.MasterData.Click("4;20");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'GenesisAutomation1.NewItemWizard' at 47;56.", repo.GenesisAutomation1.NewItemWizardInfo, new RecordItemIndex(2));
            repo.GenesisAutomation1.NewItemWizard.Click("47;56");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'PurchaseOrder.BtnNext' at 51;19.", repo.PurchaseOrder.BtnNextInfo, new RecordItemIndex(3));
            repo.PurchaseOrder.BtnNext.Click("51;19");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Wait", "Waiting 5s to exist. Associated repository item: 'PurchaseOrder.UcStep1Item.TextSelectSupplier'", repo.PurchaseOrder.UcStep1Item.TextSelectSupplierInfo, new ActionTimeout(5000), new RecordItemIndex(4));
            repo.PurchaseOrder.UcStep1Item.TextSelectSupplierInfo.WaitForExists(5000);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'PurchaseOrder.UcStep1Item.TextSelectSupplier' at 212;9.", repo.PurchaseOrder.UcStep1Item.TextSelectSupplierInfo, new RecordItemIndex(5));
            repo.PurchaseOrder.UcStep1Item.TextSelectSupplier.Click("212;9");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'GenesisAutomation.ContainerLc.PreferredSupplierRow11' at 124;6.", repo.GenesisAutomation.ContainerLc.PreferredSupplierRow11Info, new RecordItemIndex(6));
            repo.GenesisAutomation.ContainerLc.PreferredSupplierRow11.Click("124;6");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'PurchaseOrder.UcStep1Item.TextMaskBox3' at 271;11.", repo.PurchaseOrder.UcStep1Item.TextMaskBox3Info, new RecordItemIndex(7));
            repo.PurchaseOrder.UcStep1Item.TextMaskBox3.Click("271;11");
            Delay.Milliseconds(200);
            
            NewVariable = ValueConverter.ToString(Random());
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$NewVariable' with focus on 'PurchaseOrder.UcStep1Item.TextMaskBox1'.", repo.PurchaseOrder.UcStep1Item.TextMaskBox1Info, new RecordItemIndex(9));
            repo.PurchaseOrder.UcStep1Item.TextMaskBox1.PressKeys(NewVariable, 100);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'PurchaseOrder.UcStep1Item.TextMaskBox4' at 151;7.", repo.PurchaseOrder.UcStep1Item.TextMaskBox4Info, new RecordItemIndex(10));
            repo.PurchaseOrder.UcStep1Item.TextMaskBox4.Click("151;7");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Down item 'PurchaseOrder.UcStep1Item.TextMaskBox4' at 151;7.", repo.PurchaseOrder.UcStep1Item.TextMaskBox4Info, new RecordItemIndex(11));
            repo.PurchaseOrder.UcStep1Item.TextMaskBox4.MoveTo("151;7");
            Mouse.ButtonDown(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Up item 'PurchaseOrder.UcStep1Item.TextMaskBox4' at -219;1.", repo.PurchaseOrder.UcStep1Item.TextMaskBox4Info, new RecordItemIndex(12));
            repo.PurchaseOrder.UcStep1Item.TextMaskBox4.MoveTo("-219;1");
            Mouse.ButtonUp(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'test' with focus on 'PurchaseOrder.UcStep1Item.TextMaskBox4'.", repo.PurchaseOrder.UcStep1Item.TextMaskBox4Info, new RecordItemIndex(13));
            repo.PurchaseOrder.UcStep1Item.TextMaskBox4.PressKeys("test", 100);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Down}{Down}' with focus on 'PurchaseOrder.UcStep1Item.TextMaskBox4'.", repo.PurchaseOrder.UcStep1Item.TextMaskBox4Info, new RecordItemIndex(14));
            repo.PurchaseOrder.UcStep1Item.TextMaskBox4.PressKeys("{Down}{Down}", 100);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'GenesisAutomation.TESTKIT' at 296;7.", repo.GenesisAutomation.TESTKITInfo, new RecordItemIndex(15));
            repo.GenesisAutomation.TESTKIT.Click("296;7");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'PurchaseOrder.UcStep1Item.TextSelectItemGroup' at 174;6.", repo.PurchaseOrder.UcStep1Item.TextSelectItemGroupInfo, new RecordItemIndex(16));
            repo.PurchaseOrder.UcStep1Item.TextSelectItemGroup.Click("174;6");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'GenesisAutomation.DescriptionRow0' at 17;13.", repo.GenesisAutomation.DescriptionRow0Info, new RecordItemIndex(17));
            repo.GenesisAutomation.DescriptionRow0.Click("17;13");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'PurchaseOrder.UcStep1Item.Active' at 224;8.", repo.PurchaseOrder.UcStep1Item.ActiveInfo, new RecordItemIndex(18));
            repo.PurchaseOrder.UcStep1Item.Active.Click("224;8");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'GenesisAutomation.ContainerLc.CodeRow0' at 214;12.", repo.GenesisAutomation.ContainerLc.CodeRow0Info, new RecordItemIndex(19));
            repo.GenesisAutomation.ContainerLc.CodeRow0.Click("214;12");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'PurchaseOrder.UcStep1Item.TextSelectItemCategory' at 250;6.", repo.PurchaseOrder.UcStep1Item.TextSelectItemCategoryInfo, new RecordItemIndex(20));
            repo.PurchaseOrder.UcStep1Item.TextSelectItemCategory.Click("250;6");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'GenesisAutomation.ContainerLc.CodeRow0' at 94;10.", repo.GenesisAutomation.ContainerLc.CodeRow0Info, new RecordItemIndex(21));
            repo.GenesisAutomation.ContainerLc.CodeRow0.Click("94;10");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'PurchaseOrder.UcStep1Item.TextSelectItemBodySide' at 200;9.", repo.PurchaseOrder.UcStep1Item.TextSelectItemBodySideInfo, new RecordItemIndex(22));
            repo.PurchaseOrder.UcStep1Item.TextSelectItemBodySide.Click("200;9");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'GenesisAutomation.ContainerLc.DescriptionRow3' at 30;10.", repo.GenesisAutomation.ContainerLc.DescriptionRow3Info, new RecordItemIndex(23));
            repo.GenesisAutomation.ContainerLc.DescriptionRow3.Click("30;10");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'PurchaseOrder.UcStep1Item.TextSelectItemBodySite' at 218;7.", repo.PurchaseOrder.UcStep1Item.TextSelectItemBodySiteInfo, new RecordItemIndex(24));
            repo.PurchaseOrder.UcStep1Item.TextSelectItemBodySite.Click("218;7");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'GenesisAutomation.DescriptionRow9' at 41;-31.", repo.GenesisAutomation.DescriptionRow9Info, new RecordItemIndex(25));
            repo.GenesisAutomation.DescriptionRow9.Click("41;-31");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'PurchaseOrder.UcStep1Item.TextSelectAccountCode' at 196;6.", repo.PurchaseOrder.UcStep1Item.TextSelectAccountCodeInfo, new RecordItemIndex(26));
            repo.PurchaseOrder.UcStep1Item.TextSelectAccountCode.Click("196;6");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'GenesisAutomation.ContainerLc.DescriptionRow3' at 58;8.", repo.GenesisAutomation.ContainerLc.DescriptionRow3Info, new RecordItemIndex(27));
            repo.GenesisAutomation.ContainerLc.DescriptionRow3.Click("58;8");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'PurchaseOrder.UcStep1Item.TextBoxMaskBox1' at 191;10.", repo.PurchaseOrder.UcStep1Item.TextBoxMaskBox1Info, new RecordItemIndex(28));
            repo.PurchaseOrder.UcStep1Item.TextBoxMaskBox1.Click("191;10");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Back}' with focus on 'PurchaseOrder.UcStep1Item.TextBoxMaskBox1'.", repo.PurchaseOrder.UcStep1Item.TextBoxMaskBox1Info, new RecordItemIndex(29));
            repo.PurchaseOrder.UcStep1Item.TextBoxMaskBox1.PressKeys("{Back}", 100);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Back}' with focus on 'PurchaseOrder.UcStep1Item.TextBoxMaskBox1'.", repo.PurchaseOrder.UcStep1Item.TextBoxMaskBox1Info, new RecordItemIndex(30));
            repo.PurchaseOrder.UcStep1Item.TextBoxMaskBox1.PressKeys("{Back}", 100);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Down item 'PurchaseOrder.UcStep1Item.TextBoxMaskBox1' at 192;8.", repo.PurchaseOrder.UcStep1Item.TextBoxMaskBox1Info, new RecordItemIndex(31));
            repo.PurchaseOrder.UcStep1Item.TextBoxMaskBox1.MoveTo("192;8");
            Mouse.ButtonDown(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Up item 'PurchaseOrder.UcStep1Item.TextBoxMaskBox1' at 152;19.", repo.PurchaseOrder.UcStep1Item.TextBoxMaskBox1Info, new RecordItemIndex(32));
            repo.PurchaseOrder.UcStep1Item.TextBoxMaskBox1.MoveTo("152;19");
            Mouse.ButtonUp(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{NumPad1}' with focus on 'PurchaseOrder.UcStep1Item.TextBoxMaskBox1'.", repo.PurchaseOrder.UcStep1Item.TextBoxMaskBox1Info, new RecordItemIndex(33));
            repo.PurchaseOrder.UcStep1Item.TextBoxMaskBox1.PressKeys("{NumPad1}", 100);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'PurchaseOrder.ButtonNext' at 47;12.", repo.PurchaseOrder.ButtonNextInfo, new RecordItemIndex(34));
            repo.PurchaseOrder.ButtonNext.Click("47;12");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'PurchaseOrder.ButtonNext' at 36;13.", repo.PurchaseOrder.ButtonNextInfo, new RecordItemIndex(35));
            repo.PurchaseOrder.ButtonNext.Click("36;13");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'PurchaseOrder.Maximise' at 3;6.", repo.PurchaseOrder.MaximiseInfo, new RecordItemIndex(36));
            repo.PurchaseOrder.Maximise.Click("3;6");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'PurchaseOrder.WpLocationProfile.ReplenishFromRow0' at 49;15.", repo.PurchaseOrder.WpLocationProfile.ReplenishFromRow0Info, new RecordItemIndex(37));
            repo.PurchaseOrder.WpLocationProfile.ReplenishFromRow0.Click("49;15");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'PurchaseOrder.WpLocationProfile.Open' at 4;15.", repo.PurchaseOrder.WpLocationProfile.OpenInfo, new RecordItemIndex(38));
            repo.PurchaseOrder.WpLocationProfile.Open.Click("4;15");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'GenesisAutomation.ContainerLc.ReplenishFromRow6' at 110;11.", repo.GenesisAutomation.ContainerLc.ReplenishFromRow6Info, new RecordItemIndex(39));
            repo.GenesisAutomation.ContainerLc.ReplenishFromRow6.Click("110;11");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left DoubleClick item 'PurchaseOrder.WpLocationProfile.SelectionRow0' at 37;13.", repo.PurchaseOrder.WpLocationProfile.SelectionRow0Info, new RecordItemIndex(40));
            repo.PurchaseOrder.WpLocationProfile.SelectionRow0.DoubleClick("37;13");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'PurchaseOrder.ButtonNext' at 49;12.", repo.PurchaseOrder.ButtonNextInfo, new RecordItemIndex(41));
            repo.PurchaseOrder.ButtonNext.Click("49;12");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'PurchaseOrder.ButtonCreate' at 43;10.", repo.PurchaseOrder.ButtonCreateInfo, new RecordItemIndex(42));
            repo.PurchaseOrder.ButtonCreate.Click("43;10");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'GenesisAutomation1.ButtonOK' at 37;12.", repo.GenesisAutomation1.ButtonOKInfo, new RecordItemIndex(43));
            repo.GenesisAutomation1.ButtonOK.Click("37;12");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FrmMain1.Items' at 31;36.", repo.FrmMain1.ItemsInfo, new RecordItemIndex(44));
            repo.FrmMain1.Items.Click("31;36");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'GenesisAutomation1.FrmItem1.TextAllItemGroups' at 203;8.", repo.GenesisAutomation1.FrmItem1.TextAllItemGroupsInfo, new RecordItemIndex(45));
            repo.GenesisAutomation1.FrmItem1.TextAllItemGroups.Click("203;8");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'aAA' with focus on 'GenesisAutomation'.", repo.GenesisAutomation.SelfInfo, new RecordItemIndex(46));
            repo.GenesisAutomation.Self.EnsureVisible();
            Keyboard.Press("aAA", 100);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'GenesisAutomation.Find' at 30;6.", repo.GenesisAutomation.FindInfo, new RecordItemIndex(47));
            repo.GenesisAutomation.Find.Click("30;6");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'GenesisAutomation.DescriptionRow0' at 117;11.", repo.GenesisAutomation.DescriptionRow0Info, new RecordItemIndex(48));
            repo.GenesisAutomation.DescriptionRow0.Click("117;11");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'GenesisAutomation1.FrmItem1.TextAllItemCategories' at 202;7.", repo.GenesisAutomation1.FrmItem1.TextAllItemCategoriesInfo, new RecordItemIndex(49));
            repo.GenesisAutomation1.FrmItem1.TextAllItemCategories.Click("202;7");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'GenesisAutomation.ContainerLc.CodeRow0' at 57;11.", repo.GenesisAutomation.ContainerLc.CodeRow0Info, new RecordItemIndex(50));
            repo.GenesisAutomation.ContainerLc.CodeRow0.Click("57;11");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FrmMain.TextBoxMaskBox' at 240;5.", repo.FrmMain.TextBoxMaskBoxInfo, new RecordItemIndex(51));
            repo.FrmMain.TextBoxMaskBox.Click("240;5");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$NewVariable' with focus on 'FrmMain.TextBoxMaskBox'.", repo.FrmMain.TextBoxMaskBoxInfo, new RecordItemIndex(52));
            repo.FrmMain.TextBoxMaskBox.PressKeys(NewVariable, 100);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'GenesisAutomation1.FrmItem1.Find' at Center.", repo.GenesisAutomation1.FrmItem1.FindInfo, new RecordItemIndex(53));
            repo.GenesisAutomation1.FrmItem1.Find.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeContains (Text>$NewVariable) on item 'GenesisAutomation1.FrmItem1.SupplierItemCodeRow0'.", repo.GenesisAutomation1.FrmItem1.SupplierItemCodeRow0Info, new RecordItemIndex(54));
            Validate.AttributeContains(repo.GenesisAutomation1.FrmItem1.SupplierItemCodeRow0Info, "Text", NewVariable);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'GenesisAutomation1.GenesisAutomation' at 133;15.", repo.GenesisAutomation1.GenesisAutomationInfo, new RecordItemIndex(55));
            repo.GenesisAutomation1.GenesisAutomation.Click("133;15");
            Delay.Milliseconds(200);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
