///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace Genesis.Desktop.TestSuite.MasterData.Recordings
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The CreateNewItemWizardTissue recording.
    /// </summary>
    [TestModule("6fc6a469-2ee8-48d8-af11-ea18157c1304", ModuleType.Recording, 1)]
    public partial class CreateNewItemWizardTissue : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::Genesis.Desktop.TestSuite.MasterData.Genesis_Desktop_TestSuite_MasterDataRepository repository.
        /// </summary>
        public static global::Genesis.Desktop.TestSuite.MasterData.Genesis_Desktop_TestSuite_MasterDataRepository repo = global::Genesis.Desktop.TestSuite.MasterData.Genesis_Desktop_TestSuite_MasterDataRepository.Instance;

        static CreateNewItemWizardTissue instance = new CreateNewItemWizardTissue();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public CreateNewItemWizardTissue()
        {
            NewVariable = "";
            NewVariable1 = "{Back}{NumPad4}";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static CreateNewItemWizardTissue Instance
        {
            get { return instance; }
        }

#region Variables

        string _NewVariable;

        /// <summary>
        /// Gets or sets the value of variable NewVariable.
        /// </summary>
        [TestVariable("312714fe-4684-48b6-b41c-96c8d3a0dcf9")]
        public string NewVariable
        {
            get { return _NewVariable; }
            set { _NewVariable = value; }
        }

        string _NewVariable1;

        /// <summary>
        /// Gets or sets the value of variable NewVariable1.
        /// </summary>
        [TestVariable("876a92e7-c0b5-4fba-9856-439bf0b9a759")]
        public string NewVariable1
        {
            get { return _NewVariable1; }
            set { _NewVariable1 = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FrmMain.MasterData' at 12;17.", repo.FrmMain.MasterDataInfo, new RecordItemIndex(0));
            repo.FrmMain.MasterData.Click("12;17");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'GenesisAutomation1.NewItemWizard' at 47;56.", repo.GenesisAutomation1.NewItemWizardInfo, new RecordItemIndex(1));
            repo.GenesisAutomation1.NewItemWizard.Click("47;56");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'PurchaseOrder.BtnNext' at 51;19.", repo.PurchaseOrder.BtnNextInfo, new RecordItemIndex(2));
            repo.PurchaseOrder.BtnNext.Click("51;19");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Wait", "Waiting 5s to exist. Associated repository item: 'PurchaseOrder.UcStep1Item.TextSelectSupplier'", repo.PurchaseOrder.UcStep1Item.TextSelectSupplierInfo, new ActionTimeout(5000), new RecordItemIndex(3));
            repo.PurchaseOrder.UcStep1Item.TextSelectSupplierInfo.WaitForExists(5000);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'PurchaseOrder.UcStep1Item.TextSelectSupplier' at 212;9.", repo.PurchaseOrder.UcStep1Item.TextSelectSupplierInfo, new RecordItemIndex(4));
            repo.PurchaseOrder.UcStep1Item.TextSelectSupplier.Click("212;9");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'acutus' with focus on 'GenesisAutomation'.", repo.GenesisAutomation.SelfInfo, new RecordItemIndex(5));
            repo.GenesisAutomation.Self.EnsureVisible();
            Keyboard.Press("acutus", 100);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'GenesisAutomation.GridControl' at 420;32.", repo.GenesisAutomation.GridControlInfo, new RecordItemIndex(6));
            repo.GenesisAutomation.GridControl.Click("420;32");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'PurchaseOrder.UcStep1Item.TextMaskBox1' at 271;11.", repo.PurchaseOrder.UcStep1Item.TextMaskBox1Info, new RecordItemIndex(7));
            repo.PurchaseOrder.UcStep1Item.TextMaskBox1.Click("271;11");
            Delay.Milliseconds(200);
            
            NewVariable = ValueConverter.ToString(Random());
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$NewVariable' with focus on 'PurchaseOrder.UcStep1Item.TextMaskBox1'.", repo.PurchaseOrder.UcStep1Item.TextMaskBox1Info, new RecordItemIndex(9));
            repo.PurchaseOrder.UcStep1Item.TextMaskBox1.PressKeys(NewVariable, 100);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'PurchaseOrder.UcStep1Item.TextMaskBox4' at 260;8.", repo.PurchaseOrder.UcStep1Item.TextMaskBox4Info, new RecordItemIndex(10));
            repo.PurchaseOrder.UcStep1Item.TextMaskBox4.Click("260;8");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'test' with focus on 'PurchaseOrder.UcStep1Item.TextMaskBox4'.", repo.PurchaseOrder.UcStep1Item.TextMaskBox4Info, new RecordItemIndex(11));
            repo.PurchaseOrder.UcStep1Item.TextMaskBox4.PressKeys("test", 100);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'GenesisAutomation.TESTKIT' at 282;2.", repo.GenesisAutomation.TESTKITInfo, new RecordItemIndex(12));
            repo.GenesisAutomation.TESTKIT.Click("282;2");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'PurchaseOrder.UcStep1Item.TextSelectItemGroup' at 225;8.", repo.PurchaseOrder.UcStep1Item.TextSelectItemGroupInfo, new RecordItemIndex(13));
            repo.PurchaseOrder.UcStep1Item.TextSelectItemGroup.Click("225;8");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'GenesisAutomation.DescriptionRow0' at 35;13.", repo.GenesisAutomation.DescriptionRow0Info, new RecordItemIndex(14));
            repo.GenesisAutomation.DescriptionRow0.Click("35;13");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'PurchaseOrder.UcStep1Item.Active' at 208;7.", repo.PurchaseOrder.UcStep1Item.ActiveInfo, new RecordItemIndex(15));
            repo.PurchaseOrder.UcStep1Item.Active.Click("208;7");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'GenesisAutomation.ContainerLc.CodeRow0' at 97;14.", repo.GenesisAutomation.ContainerLc.CodeRow0Info, new RecordItemIndex(16));
            repo.GenesisAutomation.ContainerLc.CodeRow0.Click("97;14");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'PurchaseOrder.UcStep1Item.TextSelectItemCategory' at 261;6.", repo.PurchaseOrder.UcStep1Item.TextSelectItemCategoryInfo, new RecordItemIndex(17));
            repo.PurchaseOrder.UcStep1Item.TextSelectItemCategory.Click("261;6");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'GenesisAutomation.ContainerLc.CodeRow2' at 89;11.", repo.GenesisAutomation.ContainerLc.CodeRow2Info, new RecordItemIndex(18));
            repo.GenesisAutomation.ContainerLc.CodeRow2.Click("89;11");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'PurchaseOrder.UcStep1Item.TextSelectItemBodySide' at 152;6.", repo.PurchaseOrder.UcStep1Item.TextSelectItemBodySideInfo, new RecordItemIndex(19));
            repo.PurchaseOrder.UcStep1Item.TextSelectItemBodySide.Click("152;6");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'GenesisAutomation.ContainerLc.DescriptionRow3' at 26;9.", repo.GenesisAutomation.ContainerLc.DescriptionRow3Info, new RecordItemIndex(20));
            repo.GenesisAutomation.ContainerLc.DescriptionRow3.Click("26;9");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'PurchaseOrder.UcStep1Item.TextSelectItemBodySite' at 159;5.", repo.PurchaseOrder.UcStep1Item.TextSelectItemBodySiteInfo, new RecordItemIndex(21));
            repo.PurchaseOrder.UcStep1Item.TextSelectItemBodySite.Click("159;5");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'GenesisAutomation.DescriptionRow0' at 24;13.", repo.GenesisAutomation.DescriptionRow0Info, new RecordItemIndex(22));
            repo.GenesisAutomation.DescriptionRow0.Click("24;13");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'PurchaseOrder.UcStep1Item.TextSelectAccountCode' at 94;6.", repo.PurchaseOrder.UcStep1Item.TextSelectAccountCodeInfo, new RecordItemIndex(23));
            repo.PurchaseOrder.UcStep1Item.TextSelectAccountCode.Click("94;6");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'GenesisAutomation.ContainerLc.DescriptionRow3' at 87;12.", repo.GenesisAutomation.ContainerLc.DescriptionRow3Info, new RecordItemIndex(24));
            repo.GenesisAutomation.ContainerLc.DescriptionRow3.Click("87;12");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'PurchaseOrder.UcStep1Item.TextBoxMaskBox1' at 212;10.", repo.PurchaseOrder.UcStep1Item.TextBoxMaskBox1Info, new RecordItemIndex(25));
            repo.PurchaseOrder.UcStep1Item.TextBoxMaskBox1.Click("212;10");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Back}{NumPad1}' with focus on 'PurchaseOrder.UcStep1Item.TextBoxMaskBox1'.", repo.PurchaseOrder.UcStep1Item.TextBoxMaskBox1Info, new RecordItemIndex(26));
            repo.PurchaseOrder.UcStep1Item.TextBoxMaskBox1.PressKeys("{Back}{NumPad1}", 100);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'PurchaseOrder.UcStep1Item.TextSelectTemperatureType' at 214;10.", repo.PurchaseOrder.UcStep1Item.TextSelectTemperatureTypeInfo, new RecordItemIndex(27));
            repo.PurchaseOrder.UcStep1Item.TextSelectTemperatureType.Click("214;10");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'GenesisAutomation.TemperatureType' at 69;12.", repo.GenesisAutomation.TemperatureTypeInfo, new RecordItemIndex(28));
            repo.GenesisAutomation.TemperatureType.Click("69;12");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'PurchaseOrder.UcStep1Item.TextBoxMaskBox' at 256;8.", repo.PurchaseOrder.UcStep1Item.TextBoxMaskBoxInfo, new RecordItemIndex(29));
            repo.PurchaseOrder.UcStep1Item.TextBoxMaskBox.Click("256;8");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{NumPad0}' with focus on 'PurchaseOrder.UcStep1Item.TextBoxMaskBox'.", repo.PurchaseOrder.UcStep1Item.TextBoxMaskBoxInfo, new RecordItemIndex(30));
            repo.PurchaseOrder.UcStep1Item.TextBoxMaskBox.PressKeys("{NumPad0}", 100);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'PurchaseOrder.UcStep1Item.TextBoxMaskBox2' at 256;9.", repo.PurchaseOrder.UcStep1Item.TextBoxMaskBox2Info, new RecordItemIndex(31));
            repo.PurchaseOrder.UcStep1Item.TextBoxMaskBox2.Click("256;9");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$NewVariable1' with focus on 'PurchaseOrder.UcStep1Item.TextBoxMaskBox2'.", repo.PurchaseOrder.UcStep1Item.TextBoxMaskBox2Info, new RecordItemIndex(32));
            repo.PurchaseOrder.UcStep1Item.TextBoxMaskBox2.PressKeys(NewVariable1, 100);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Down item 'PurchaseOrder.UcStep1Item.TextBoxMaskBox2' at 244;8.", repo.PurchaseOrder.UcStep1Item.TextBoxMaskBox2Info, new RecordItemIndex(33));
            repo.PurchaseOrder.UcStep1Item.TextBoxMaskBox2.MoveTo("244;8");
            Mouse.ButtonDown(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Up item 'PurchaseOrder.UcStep1Item.TextBoxMaskBox2' at 394;-10.", repo.PurchaseOrder.UcStep1Item.TextBoxMaskBox2Info, new RecordItemIndex(34));
            repo.PurchaseOrder.UcStep1Item.TextBoxMaskBox2.MoveTo("394;-10");
            Mouse.ButtonUp(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{NumPad4}' with focus on 'PurchaseOrder.UcStep1Item.TextBoxMaskBox2'.", repo.PurchaseOrder.UcStep1Item.TextBoxMaskBox2Info, new RecordItemIndex(35));
            repo.PurchaseOrder.UcStep1Item.TextBoxMaskBox2.PressKeys("{NumPad4}", 100);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'PurchaseOrder.ButtonNext' at 46;9.", repo.PurchaseOrder.ButtonNextInfo, new RecordItemIndex(36));
            repo.PurchaseOrder.ButtonNext.Click("46;9");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'PurchaseOrder.ButtonNext' at 33;12.", repo.PurchaseOrder.ButtonNextInfo, new RecordItemIndex(37));
            repo.PurchaseOrder.ButtonNext.Click("33;12");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'PurchaseOrder.Maximise' at 4;9.", repo.PurchaseOrder.MaximiseInfo, new RecordItemIndex(38));
            repo.PurchaseOrder.Maximise.Click("4;9");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'PurchaseOrder.WpLocationProfile.ReplenishFromRow0' at 20;14.", repo.PurchaseOrder.WpLocationProfile.ReplenishFromRow0Info, new RecordItemIndex(39));
            repo.PurchaseOrder.WpLocationProfile.ReplenishFromRow0.Click("20;14");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'GenesisAutomation.ContainerLc.ReplenishFromRow6' at 62;14.", repo.GenesisAutomation.ContainerLc.ReplenishFromRow6Info, new RecordItemIndex(40));
            repo.GenesisAutomation.ContainerLc.ReplenishFromRow6.Click("62;14");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left DoubleClick item 'PurchaseOrder.WpLocationProfile.SelectionRow0' at 38;15.", repo.PurchaseOrder.WpLocationProfile.SelectionRow0Info, new RecordItemIndex(41));
            repo.PurchaseOrder.WpLocationProfile.SelectionRow0.DoubleClick("38;15");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'PurchaseOrder.BtnNext' at 58;12.", repo.PurchaseOrder.BtnNextInfo, new RecordItemIndex(42));
            repo.PurchaseOrder.BtnNext.Click("58;12");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'PurchaseOrder.BtnFinish' at 58;12.", repo.PurchaseOrder.BtnFinishInfo, new RecordItemIndex(43));
            repo.PurchaseOrder.BtnFinish.Click("58;12");
            Delay.Milliseconds(200);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'PurchaseOrder.ButtonCreate' at 43;10.", repo.PurchaseOrder.ButtonCreateInfo, new RecordItemIndex(44));
            //repo.PurchaseOrder.ButtonCreate.Click("43;10");
            //Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'GenesisAutomation1.ButtonOK' at 37;12.", repo.GenesisAutomation1.ButtonOKInfo, new RecordItemIndex(45));
            repo.GenesisAutomation1.ButtonOK.Click("37;12");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FrmMain1.Items' at 31;36.", repo.FrmMain1.ItemsInfo, new RecordItemIndex(46));
            repo.FrmMain1.Items.Click("31;36");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'GenesisAutomation1.FrmItem1.TextAllItemGroups' at 203;8.", repo.GenesisAutomation1.FrmItem1.TextAllItemGroupsInfo, new RecordItemIndex(47));
            repo.GenesisAutomation1.FrmItem1.TextAllItemGroups.Click("203;8");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'AAA' with focus on 'GenesisAutomation'.", repo.GenesisAutomation.SelfInfo, new RecordItemIndex(48));
            repo.GenesisAutomation.Self.EnsureVisible();
            Keyboard.Press("AAA", 100);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'GenesisAutomation.Find' at 30;6.", repo.GenesisAutomation.FindInfo, new RecordItemIndex(49));
            repo.GenesisAutomation.Find.Click("30;6");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'GenesisAutomation.DescriptionRow0' at 117;11.", repo.GenesisAutomation.DescriptionRow0Info, new RecordItemIndex(50));
            repo.GenesisAutomation.DescriptionRow0.Click("117;11");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'GenesisAutomation1.FrmItem1.TextAllItemCategories' at 202;7.", repo.GenesisAutomation1.FrmItem1.TextAllItemCategoriesInfo, new RecordItemIndex(51));
            repo.GenesisAutomation1.FrmItem1.TextAllItemCategories.Click("202;7");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'GenesisAutomation.ContainerLc.CodeRow2' at 57;11.", repo.GenesisAutomation.ContainerLc.CodeRow2Info, new RecordItemIndex(52));
            repo.GenesisAutomation.ContainerLc.CodeRow2.Click("57;11");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FrmMain.TextBoxMaskBox' at 240;5.", repo.FrmMain.TextBoxMaskBoxInfo, new RecordItemIndex(53));
            repo.FrmMain.TextBoxMaskBox.Click("240;5");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$NewVariable' with focus on 'FrmMain.TextBoxMaskBox'.", repo.FrmMain.TextBoxMaskBoxInfo, new RecordItemIndex(54));
            repo.FrmMain.TextBoxMaskBox.PressKeys(NewVariable, 100);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'GenesisAutomation1.FrmItem1.Find' at Center.", repo.GenesisAutomation1.FrmItem1.FindInfo, new RecordItemIndex(55));
            repo.GenesisAutomation1.FrmItem1.Find.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeContains (Text>$NewVariable) on item 'GenesisAutomation1.FrmItem1.SupplierItemCodeRow0'.", repo.GenesisAutomation1.FrmItem1.SupplierItemCodeRow0Info, new RecordItemIndex(56));
            Validate.AttributeContains(repo.GenesisAutomation1.FrmItem1.SupplierItemCodeRow0Info, "Text", NewVariable);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'GenesisAutomation1.GenesisAutomation' at 133;15.", repo.GenesisAutomation1.GenesisAutomationInfo, new RecordItemIndex(57));
            repo.GenesisAutomation1.GenesisAutomation.Click("133;15");
            Delay.Milliseconds(200);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
