///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace Genesis.Desktop.TestSuite.MasterData.Recordings
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The DeleteImportedItemSingle recording.
    /// </summary>
    [TestModule("dec8d4a7-05fe-486c-aff0-ec9aaaf0de23", ModuleType.Recording, 1)]
    public partial class DeleteImportedItemSingle : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::Genesis.Desktop.TestSuite.MasterData.Genesis_Desktop_TestSuite_MasterDataRepository repository.
        /// </summary>
        public static global::Genesis.Desktop.TestSuite.MasterData.Genesis_Desktop_TestSuite_MasterDataRepository repo = global::Genesis.Desktop.TestSuite.MasterData.Genesis_Desktop_TestSuite_MasterDataRepository.Instance;

        static DeleteImportedItemSingle instance = new DeleteImportedItemSingle();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public DeleteImportedItemSingle()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static DeleteImportedItemSingle Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FrmMain.LayoutControl1.Open' at 6;9.", repo.FrmMain.LayoutControl1.OpenInfo, new RecordItemIndex(0));
            repo.FrmMain.LayoutControl1.Open.Click("6;9");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FrmMain.LayoutControl1.Close' at -91;50.", repo.FrmMain.LayoutControl1.CloseInfo, new RecordItemIndex(1));
            repo.FrmMain.LayoutControl1.Close.Click("-91;50");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'aaa' with focus on 'GenesisAutomation'.", repo.GenesisAutomation.SelfInfo, new RecordItemIndex(2));
            repo.GenesisAutomation.Self.EnsureVisible();
            Keyboard.Press("aaa");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'GenesisAutomation.Find' at 40;10.", repo.GenesisAutomation.FindInfo, new RecordItemIndex(3));
            repo.GenesisAutomation.Find.Click("40;10");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'GenesisAutomation.Row1' at 6;8.", repo.GenesisAutomation.Row1Info, new RecordItemIndex(4));
            repo.GenesisAutomation.Row1.Click("6;8");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FrmMain.TextBoxMaskBox' at 147;6.", repo.FrmMain.TextBoxMaskBoxInfo, new RecordItemIndex(5));
            repo.FrmMain.TextBoxMaskBox.Click("147;6");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'b27rq' with focus on 'FrmMain.TextBoxMaskBox'.", repo.FrmMain.TextBoxMaskBoxInfo, new RecordItemIndex(6));
            repo.FrmMain.TextBoxMaskBox.PressKeys("b27rq");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FrmMain.LayoutControl1.DeleteRow0' at 24;17.", repo.FrmMain.LayoutControl1.DeleteRow0Info, new RecordItemIndex(7));
            repo.FrmMain.LayoutControl1.DeleteRow0.Click("24;17");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'PurchaseOrder.ButtonYes1' at 36;10.", repo.PurchaseOrder.ButtonYes1Info, new RecordItemIndex(8));
            repo.PurchaseOrder.ButtonYes1.Click("36;10");
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
