///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace Genesis.Desktop.TestSuite.Inventory.Recordings
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The GoodsReceiptReceiveAll recording.
    /// </summary>
    [TestModule("f7c12ff7-8a3e-4536-93b4-a834bc85705d", ModuleType.Recording, 1)]
    public partial class GoodsReceiptReceiveAll : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::Genesis.Desktop.TestSuite.Inventory.Genesis_Desktop_TestSuite_InventoryRepository repository.
        /// </summary>
        public static global::Genesis.Desktop.TestSuite.Inventory.Genesis_Desktop_TestSuite_InventoryRepository repo = global::Genesis.Desktop.TestSuite.Inventory.Genesis_Desktop_TestSuite_InventoryRepository.Instance;

        static GoodsReceiptReceiveAll instance = new GoodsReceiptReceiveAll();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public GoodsReceiptReceiveAll()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static GoodsReceiptReceiveAll Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FrmMain.CreateRequisition' at 51;22.", repo.FrmMain.CreateRequisitionInfo, new RecordItemIndex(0));
            repo.FrmMain.CreateRequisition.Click("51;22");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FrmCreateRequisition.Open' at 8;11.", repo.FrmCreateRequisition.OpenInfo, new RecordItemIndex(1));
            repo.FrmCreateRequisition.Open.Click("8;11");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'GenesisAutomation.TextMaskBox' at 124;9.", repo.GenesisAutomation.TextMaskBoxInfo, new RecordItemIndex(2));
            repo.GenesisAutomation.TextMaskBox.Click("124;9");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'vh' with focus on 'GenesisAutomation.TextMaskBox'.", repo.GenesisAutomation.TextMaskBoxInfo, new RecordItemIndex(3));
            repo.GenesisAutomation.TextMaskBox.PressKeys("vh");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '0010' with focus on 'GenesisAutomation.TextMaskBox'.", repo.GenesisAutomation.TextMaskBoxInfo, new RecordItemIndex(4));
            repo.GenesisAutomation.TextMaskBox.PressKeys("0010");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'GenesisAutomation.Row1' at 9;9.", repo.GenesisAutomation.Row1Info, new RecordItemIndex(5));
            repo.GenesisAutomation.Row1.Click("9;9");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FrmCreateRequisition.Open1' at 6;18.", repo.FrmCreateRequisition.Open1Info, new RecordItemIndex(6));
            repo.FrmCreateRequisition.Open1.Click("6;18");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'GenesisAutomation.TextMaskBox' at 133;7.", repo.GenesisAutomation.TextMaskBoxInfo, new RecordItemIndex(7));
            repo.GenesisAutomation.TextMaskBox.Click("133;7");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'fcc617' with focus on 'GenesisAutomation.TextMaskBox'.", repo.GenesisAutomation.TextMaskBoxInfo, new RecordItemIndex(8));
            repo.GenesisAutomation.TextMaskBox.PressKeys("fcc617");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'GenesisAutomation.Row1' at 9;11.", repo.GenesisAutomation.Row1Info, new RecordItemIndex(9));
            repo.GenesisAutomation.Row1.Click("9;11");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FrmCreateRequisition.AddRequisition' at 75;19.", repo.FrmCreateRequisition.AddRequisitionInfo, new RecordItemIndex(10));
            repo.FrmCreateRequisition.AddRequisition.Click("75;19");
            Delay.Milliseconds(0);
            
            try {
                Report.Log(ReportLevel.Info, "Mouse", "(Optional Action)\r\nMouse Left Click item 'GenesisAutomation1.ButtonYes' at 38;12.", repo.GenesisAutomation1.ButtonYesInfo, new RecordItemIndex(11));
                repo.GenesisAutomation1.ButtonYes.Click("38;12");
                Delay.Milliseconds(0);
            } catch(Exception ex) { Report.Log(ReportLevel.Warn, "Module", "(Optional Action) " + ex.Message, new RecordItemIndex(11)); }
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FrmCreateRequisition.Open' at 6;20.", repo.FrmCreateRequisition.OpenInfo, new RecordItemIndex(12));
            repo.FrmCreateRequisition.Open.Click("6;20");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'GenesisAutomation.TextMaskBox' at 134;9.", repo.GenesisAutomation.TextMaskBoxInfo, new RecordItemIndex(13));
            repo.GenesisAutomation.TextMaskBox.Click("134;9");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'vh0015' with focus on 'GenesisAutomation.TextMaskBox'.", repo.GenesisAutomation.TextMaskBoxInfo, new RecordItemIndex(14));
            repo.GenesisAutomation.TextMaskBox.PressKeys("vh0015");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'GenesisAutomation.Row1' at 4;9.", repo.GenesisAutomation.Row1Info, new RecordItemIndex(15));
            repo.GenesisAutomation.Row1.Click("4;9");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FrmCreateRequisition.Open1' at 9;19.", repo.FrmCreateRequisition.Open1Info, new RecordItemIndex(16));
            repo.FrmCreateRequisition.Open1.Click("9;19");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'GenesisAutomation.TextMaskBox1' at 139;5.", repo.GenesisAutomation.TextMaskBox1Info, new RecordItemIndex(17));
            repo.GenesisAutomation.TextMaskBox1.Click("139;5");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'ff' with focus on 'GenesisAutomation.TextMaskBox1'.", repo.GenesisAutomation.TextMaskBox1Info, new RecordItemIndex(18));
            repo.GenesisAutomation.TextMaskBox1.PressKeys("ff");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'e062' with focus on 'GenesisAutomation.TextMaskBox1'.", repo.GenesisAutomation.TextMaskBox1Info, new RecordItemIndex(19));
            repo.GenesisAutomation.TextMaskBox1.PressKeys("e062");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'GenesisAutomation.Row1' at 7;8.", repo.GenesisAutomation.Row1Info, new RecordItemIndex(20));
            repo.GenesisAutomation.Row1.Click("7;8");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FrmCreateRequisition.AddRequisition' at 85;11.", repo.FrmCreateRequisition.AddRequisitionInfo, new RecordItemIndex(21));
            repo.FrmCreateRequisition.AddRequisition.Click("85;11");
            Delay.Milliseconds(0);
            
            try {
                Report.Log(ReportLevel.Info, "Mouse", "(Optional Action)\r\nMouse Left Click item 'GenesisAutomation1.ButtonYes' at 38;9.", repo.GenesisAutomation1.ButtonYesInfo, new RecordItemIndex(22));
                repo.GenesisAutomation1.ButtonYes.Click("38;9");
                Delay.Milliseconds(0);
            } catch(Exception ex) { Report.Log(ReportLevel.Warn, "Module", "(Optional Action) " + ex.Message, new RecordItemIndex(22)); }
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FrmCreateRequisition.Confirm' at 101;13.", repo.FrmCreateRequisition.ConfirmInfo, new RecordItemIndex(23));
            repo.FrmCreateRequisition.Confirm.Click("101;13");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'GenesisAutomation1.ButtonOK' at 36;8.", repo.GenesisAutomation1.ButtonOKInfo, new RecordItemIndex(24));
            repo.GenesisAutomation1.ButtonOK.Click("36;8");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FrmMain.NewOrders' at 51;12.", repo.FrmMain.NewOrdersInfo, new RecordItemIndex(25));
            repo.FrmMain.NewOrders.Click("51;12");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FrmMain.ReleaseRow0' at 29;12.", repo.FrmMain.ReleaseRow0Info, new RecordItemIndex(26));
            repo.FrmMain.ReleaseRow0.Click("29;12");
            Delay.Milliseconds(0);
            
            try {
                Report.Log(ReportLevel.Info, "Mouse", "(Optional Action)\r\nMouse Left Click item 'PurchaseOrder.ButtonOK' at 34;7.", repo.PurchaseOrder.ButtonOKInfo, new RecordItemIndex(27));
                repo.PurchaseOrder.ButtonOK.Click("34;7");
                Delay.Milliseconds(0);
            } catch(Exception ex) { Report.Log(ReportLevel.Warn, "Module", "(Optional Action) " + ex.Message, new RecordItemIndex(27)); }
            
            try {
                Report.Log(ReportLevel.Info, "Mouse", "(Optional Action)\r\nMouse Left Click item 'GenesisAutomation1.ButtonYes' at 34;7.", repo.GenesisAutomation1.ButtonYesInfo, new RecordItemIndex(28));
                repo.GenesisAutomation1.ButtonYes.Click("34;7");
                Delay.Milliseconds(0);
            } catch(Exception ex) { Report.Log(ReportLevel.Warn, "Module", "(Optional Action) " + ex.Message, new RecordItemIndex(28)); }
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FrmMain.SplitControl.OutstandingOrders' at 86;12.", repo.FrmMain.SplitControl.OutstandingOrdersInfo, new RecordItemIndex(29));
            repo.FrmMain.SplitControl.OutstandingOrders.Click("86;12");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FrmMain.SplitControl.GoodsReceiptRow0' at 31;11.", repo.FrmMain.SplitControl.GoodsReceiptRow0Info, new RecordItemIndex(30));
            repo.FrmMain.SplitControl.GoodsReceiptRow0.Click("31;11");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'PurchaseOrder.TextMaskBox2' at 389;8.", repo.PurchaseOrder.TextMaskBox2Info, new RecordItemIndex(31));
            repo.PurchaseOrder.TextMaskBox2.Click("389;8");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'receive all' with focus on 'PurchaseOrder.TextMaskBox2'.", repo.PurchaseOrder.TextMaskBox2Info, new RecordItemIndex(32));
            repo.PurchaseOrder.TextMaskBox2.PressKeys("receive all");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'PurchaseOrder.ReceiveAll' at 84;15.", repo.PurchaseOrder.ReceiveAllInfo, new RecordItemIndex(33));
            repo.PurchaseOrder.ReceiveAll.Click("84;15");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'GenesisAutomation1.ButtonNo' at 36;10.", repo.GenesisAutomation1.ButtonNoInfo, new RecordItemIndex(34));
            repo.GenesisAutomation1.ButtonNo.Click("36;10");
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
