///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace Genesis.Desktop.TestSuite.Inventory.Recordings
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The ReleaseRequisition recording.
    /// </summary>
    [TestModule("f5e7b160-f7fc-4b51-b938-4f58881a8219", ModuleType.Recording, 1)]
    public partial class ReleaseRequisition : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::Genesis.Desktop.TestSuite.Inventory.Genesis_Desktop_TestSuite_InventoryRepository repository.
        /// </summary>
        public static global::Genesis.Desktop.TestSuite.Inventory.Genesis_Desktop_TestSuite_InventoryRepository repo = global::Genesis.Desktop.TestSuite.Inventory.Genesis_Desktop_TestSuite_InventoryRepository.Instance;

        static ReleaseRequisition instance = new ReleaseRequisition();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public ReleaseRequisition()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static ReleaseRequisition Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FrmMain.NewOrders' at 46;19.", repo.FrmMain.NewOrdersInfo, new RecordItemIndex(0));
            repo.FrmMain.NewOrders.Click("46;19");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FrmMain.ReleaseRow0' at 32;11.", repo.FrmMain.ReleaseRow0Info, new RecordItemIndex(1));
            repo.FrmMain.ReleaseRow0.Click("32;11");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'GenesisAutomation1.ButtonYes'.", repo.GenesisAutomation1.ButtonYesInfo, new RecordItemIndex(2));
            Validate.Exists(repo.GenesisAutomation1.ButtonYesInfo);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'GenesisAutomation1.ButtonYes' at 34;12.", repo.GenesisAutomation1.ButtonYesInfo, new RecordItemIndex(3));
            repo.GenesisAutomation1.ButtonYes.Click("34;12");
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
