///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace Genesis.Desktop.TestSuite.Inventory.Recordings
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The StockTakeAdd recording.
    /// </summary>
    [TestModule("d42c8636-66e4-4def-aa7f-b3042a665e2a", ModuleType.Recording, 1)]
    public partial class StockTakeAdd : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::Genesis.Desktop.TestSuite.Inventory.Genesis_Desktop_TestSuite_InventoryRepository repository.
        /// </summary>
        public static global::Genesis.Desktop.TestSuite.Inventory.Genesis_Desktop_TestSuite_InventoryRepository repo = global::Genesis.Desktop.TestSuite.Inventory.Genesis_Desktop_TestSuite_InventoryRepository.Instance;

        static StockTakeAdd instance = new StockTakeAdd();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public StockTakeAdd()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static StockTakeAdd Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'GenesisAutomation1.StockTake' at 25;14.", repo.GenesisAutomation1.StockTakeInfo, new RecordItemIndex(0));
            repo.GenesisAutomation1.StockTake.Click("25;14");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'GenesisAutomation1.NewStockTake' at 81;14.", repo.GenesisAutomation1.NewStockTakeInfo, new RecordItemIndex(1));
            repo.GenesisAutomation1.NewStockTake.Click("81;14");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'PurchaseOrder.Part' at 9;1.", repo.PurchaseOrder.PartInfo, new RecordItemIndex(2));
            repo.PurchaseOrder.Part.Click("9;1");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'PurchaseOrder.LayoutControl1.ButtonNext' at 31;10.", repo.PurchaseOrder.LayoutControl1.ButtonNextInfo, new RecordItemIndex(3));
            repo.PurchaseOrder.LayoutControl1.ButtonNext.Click("31;10");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'PurchaseOrder.WizardControl1' at 435;233.", repo.PurchaseOrder.WizardControl1Info, new RecordItemIndex(4));
            repo.PurchaseOrder.WizardControl1.Click("435;233");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'aur' with focus on 'PurchaseOrder'.", repo.PurchaseOrder.SelfInfo, new RecordItemIndex(5));
            repo.PurchaseOrder.Self.EnsureVisible();
            Keyboard.Press("aur");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Back}' with focus on 'PurchaseOrder'.", repo.PurchaseOrder.SelfInfo, new RecordItemIndex(6));
            repo.PurchaseOrder.Self.EnsureVisible();
            Keyboard.Press("{Back}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'tomation' with focus on 'PurchaseOrder'.", repo.PurchaseOrder.SelfInfo, new RecordItemIndex(7));
            repo.PurchaseOrder.Self.EnsureVisible();
            Keyboard.Press("tomation");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'PurchaseOrder.LayoutControl1.ButtonNext' at 44;3.", repo.PurchaseOrder.LayoutControl1.ButtonNextInfo, new RecordItemIndex(8));
            repo.PurchaseOrder.LayoutControl1.ButtonNext.Click("44;3");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'PurchaseOrder.LayoutControl1.ChooseItems' at 56;17.", repo.PurchaseOrder.LayoutControl1.ChooseItemsInfo, new RecordItemIndex(9));
            repo.PurchaseOrder.LayoutControl1.ChooseItems.Click("56;17");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'PurchaseOrder.DdlSublocationsMulti' at 267;8.", repo.PurchaseOrder.DdlSublocationsMultiInfo, new RecordItemIndex(10));
            repo.PurchaseOrder.DdlSublocationsMulti.Click("267;8");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'GenesisAutomation.Row2' at 7;8.", repo.GenesisAutomation.Row2Info, new RecordItemIndex(11));
            repo.GenesisAutomation.Row2.Click("7;8");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'GenesisAutomation.Cancel' at 9;5.", repo.GenesisAutomation.CancelInfo, new RecordItemIndex(12));
            repo.GenesisAutomation.Cancel.Click("9;5");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'PurchaseOrder.LayoutControl1.Mark' at 33;19.", repo.PurchaseOrder.LayoutControl1.MarkInfo, new RecordItemIndex(13));
            repo.PurchaseOrder.LayoutControl1.Mark.Click("33;19");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'PurchaseOrder.LayoutControl1.AddSelected' at 112;14.", repo.PurchaseOrder.LayoutControl1.AddSelectedInfo, new RecordItemIndex(14));
            repo.PurchaseOrder.LayoutControl1.AddSelected.Click("112;14");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'PurchaseOrder.LayoutControl1.ButtonNext' at 33;5.", repo.PurchaseOrder.LayoutControl1.ButtonNextInfo, new RecordItemIndex(15));
            repo.PurchaseOrder.LayoutControl1.ButtonNext.Click("33;5");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'PurchaseOrder.LayoutControl1.ButtonFinish' at 34;13.", repo.PurchaseOrder.LayoutControl1.ButtonFinishInfo, new RecordItemIndex(16));
            repo.PurchaseOrder.LayoutControl1.ButtonFinish.Click("34;13");
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
