///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace Genesis.Desktop.TestSuite.Inventory.Recordings
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The StockTakeSubmit recording.
    /// </summary>
    [TestModule("602b14dc-060e-4a48-b847-4fc295313916", ModuleType.Recording, 1)]
    public partial class StockTakeSubmit : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::Genesis.Desktop.TestSuite.Inventory.Genesis_Desktop_TestSuite_InventoryRepository repository.
        /// </summary>
        public static global::Genesis.Desktop.TestSuite.Inventory.Genesis_Desktop_TestSuite_InventoryRepository repo = global::Genesis.Desktop.TestSuite.Inventory.Genesis_Desktop_TestSuite_InventoryRepository.Instance;

        static StockTakeSubmit instance = new StockTakeSubmit();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public StockTakeSubmit()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static StockTakeSubmit Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'GenesisAutomation1.StockTake' at 25;14.", repo.GenesisAutomation1.StockTakeInfo, new RecordItemIndex(0));
            repo.GenesisAutomation1.StockTake.Click("25;14");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'GenesisAutomation1.AmendRow0' at 25;8.", repo.GenesisAutomation1.AmendRow0Info, new RecordItemIndex(1));
            repo.GenesisAutomation1.AmendRow0.Click("25;8");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 3s.", new RecordItemIndex(2));
            Delay.Duration(3000, false);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'GenesisAutomation1.MdiClient' at 143;15.", repo.GenesisAutomation1.MdiClientInfo, new RecordItemIndex(3));
            //repo.GenesisAutomation1.MdiClient.Click("143;15");
            //Delay.Milliseconds(0);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'GenesisAutomation1.MdiClient' at 161;15.", repo.GenesisAutomation1.MdiClientInfo, new RecordItemIndex(4));
            //repo.GenesisAutomation1.MdiClient.Click("161;15");
            //Delay.Milliseconds(0);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'GenesisAutomation1.MdiClient' at 42;17.", repo.GenesisAutomation1.MdiClientInfo, new RecordItemIndex(5));
            //repo.GenesisAutomation1.MdiClient.Click("42;17");
            //Delay.Milliseconds(0);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'GenesisAutomation1.MdiClient' at 67;18.", repo.GenesisAutomation1.MdiClientInfo, new RecordItemIndex(6));
            //repo.GenesisAutomation1.MdiClient.Click("67;18");
            //Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'GenesisAutomation1.FrmStockTakeAmend.LciProgressPanel' at 52;15.", repo.GenesisAutomation1.FrmStockTakeAmend.LciProgressPanelInfo, new RecordItemIndex(7));
            repo.GenesisAutomation1.FrmStockTakeAmend.LciProgressPanel.Click("52;15");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Right}' with focus on 'GenesisAutomation1'.", repo.GenesisAutomation1.SelfInfo, new RecordItemIndex(8));
            repo.GenesisAutomation1.Self.EnsureVisible();
            Keyboard.Press("{Right}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'GenesisAutomation1.FrmStockTakeAmend.CountedQtyRow0' at 37;14.", repo.GenesisAutomation1.FrmStockTakeAmend.CountedQtyRow0Info, new RecordItemIndex(9));
            repo.GenesisAutomation1.FrmStockTakeAmend.CountedQtyRow0.Click("37;14");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '12' with focus on 'GenesisAutomation1.FrmStockTakeAmend.CountedQtyRow0'.", repo.GenesisAutomation1.FrmStockTakeAmend.CountedQtyRow0Info, new RecordItemIndex(10));
            repo.GenesisAutomation1.FrmStockTakeAmend.CountedQtyRow0.PressKeys("12");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Down}7{Down}' with focus on 'GenesisAutomation1.FrmStockTakeAmend.CountedQtyRow0'.", repo.GenesisAutomation1.FrmStockTakeAmend.CountedQtyRow0Info, new RecordItemIndex(11));
            repo.GenesisAutomation1.FrmStockTakeAmend.CountedQtyRow0.PressKeys("{Down}7{Down}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '7{Down}9{Down}4' with focus on 'GenesisAutomation1.FrmStockTakeAmend.CountedQtyRow0'.", repo.GenesisAutomation1.FrmStockTakeAmend.CountedQtyRow0Info, new RecordItemIndex(12));
            repo.GenesisAutomation1.FrmStockTakeAmend.CountedQtyRow0.PressKeys("7{Down}9{Down}4");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Down}11{Down}11' with focus on 'GenesisAutomation1.FrmStockTakeAmend.CountedQtyRow0'.", repo.GenesisAutomation1.FrmStockTakeAmend.CountedQtyRow0Info, new RecordItemIndex(13));
            repo.GenesisAutomation1.FrmStockTakeAmend.CountedQtyRow0.PressKeys("{Down}11{Down}11");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'GenesisAutomation1.FrmStockTakeAmend.HeaderPanel' at 57;13.", repo.GenesisAutomation1.FrmStockTakeAmend.HeaderPanelInfo, new RecordItemIndex(14));
            repo.GenesisAutomation1.FrmStockTakeAmend.HeaderPanel.Click("57;13");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'GenesisAutomation1.FrmStockTakeAmend.Submit7Items' at 103;8.", repo.GenesisAutomation1.FrmStockTakeAmend.Submit7ItemsInfo, new RecordItemIndex(15));
            repo.GenesisAutomation1.FrmStockTakeAmend.Submit7Items.Click("103;8");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'GenesisAutomation1.ButtonYes' at 37;11.", repo.GenesisAutomation1.ButtonYesInfo, new RecordItemIndex(16));
            repo.GenesisAutomation1.ButtonYes.Click("37;11");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'GenesisAutomation1.FrmStockTakeAmend.CloseWindow' at 112;19.", repo.GenesisAutomation1.FrmStockTakeAmend.CloseWindowInfo, new RecordItemIndex(17));
            repo.GenesisAutomation1.FrmStockTakeAmend.CloseWindow.Click("112;19");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 3s.", new RecordItemIndex(18));
            Delay.Duration(3000, false);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
